/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:37 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ASTextNodeDelegate <NSObject>
@optional
-(void)textNode:(id)arg1 tappedLinkAttribute:(id)arg2 value:(id)arg3 atPoint:(CGPoint)arg4 textRange:(NSRange)arg5;
-(void)textNode:(id)arg1 longPressedLinkAttribute:(id)arg2 value:(id)arg3 atPoint:(CGPoint)arg4 textRange:(NSRange)arg5;
-(void)textNodeTappedTruncationToken:(id)arg1;
-(BOOL)textNode:(id)arg1 shouldHighlightLinkAttribute:(id)arg2 value:(id)arg3 atPoint:(CGPoint)arg4;
-(BOOL)textNode:(id)arg1 shouldLongPressLinkAttribute:(id)arg2 value:(id)arg3 atPoint:(CGPoint)arg4;

@end

