/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:39 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBUserSession, NSString, FBGenericFetcher;

@interface FBInstantGameGamePlayerStateDataNetworker : NSObject {

	FBUserSession* _session;
	NSString* _gameID;
	FBGenericFetcher* _genericFetcher;

}
-(id)initWithSession:(id)arg1 gameID:(id)arg2 ;
-(void)savePlayerState:(id)arg1 failureBlock:(/*^block*/id)arg2 ;
-(void)fetchPlayerStateWithCallbackQueue:(id)arg1 successBlock:(/*^block*/id)arg2 failureBlock:(/*^block*/id)arg3 ;
@end

