/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:40 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBNuxTooltipView.h>

@protocol FBMagicStoryNuxViewDelegate;
@interface FBMagicStoryNuxView : FBNuxTooltipView {

	id<FBMagicStoryNuxViewDelegate> _magicStoryDelegate;

}

@property (assign,nonatomic,__weak) id<FBMagicStoryNuxViewDelegate> magicStoryDelegate;              //@synthesize magicStoryDelegate=_magicStoryDelegate - In the implementation block
-(id<FBMagicStoryNuxViewDelegate>)magicStoryDelegate;
-(void)setMagicStoryDelegate:(id<FBMagicStoryNuxViewDelegate>)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
@end

