/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:41 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBMPCompositeFilter.h>

@class NSArray;

@interface FBMPMultiplexer : FBMPCompositeFilter {

	NSArray* _multiplexedConsumerPorts;

}
+(id)_newWithMultiplexedConsumerPortDataTypes:(id)arg1 producerPortDataType:(Class)arg2 multiplexQueue:(id)arg3 block:(/*^block*/id)arg4 ;
+(id)newWithMultiplexedConsumerPortDataTypes:(id)arg1 producerPortDataType:(Class)arg2 multiplexQueue:(id)arg3 block:(/*^block*/id)arg4 ;
+(id)newWithMultiplexedConsumerPortDataType:(Class)arg1 consumerPortsCount:(unsigned long long)arg2 producerPortDataType:(Class)arg3 block:(/*^block*/id)arg4 ;
-(id)consumerPorts;
@end

