/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:40 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBCache;

@interface FBMQTTClientByteAggregator : NSObject {

	FBCache* _totalReadBytesByConn;
	FBCache* _totalWriteBytesByConn;

}
-(id)_calculateChangeInWriteBytes:(long long)arg1 rawBytesWritten:(id)arg2 foreground:(BOOL)arg3 ;
-(id)_calculateChangeInReadBytes:(long long)arg1 rawBytesRead:(id)arg2 foreground:(BOOL)arg3 ;
-(void)onAggregateForConnection:(long long)arg1 rawBytesWritten:(id)arg2 foreground:(BOOL)arg3 ;
-(void)onAggregateForConnection:(long long)arg1 rawBytesRead:(id)arg2 foreground:(BOOL)arg3 ;
-(void)onAggregateForDisconnectedConnection:(long long)arg1 rawBytesWritten:(id)arg2 rawBytesRead:(id)arg3 foreground:(BOOL)arg4 ;
-(id)init;
@end

