/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:41 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBAttachmentController.h>
#import <Messenger/FBOpenableAttachmentNodeDelegate.h>

@class NSString;

@interface FBOpenableAttachmentController : FBAttachmentController <FBOpenableAttachmentNodeDelegate>

@property (assign,nonatomic,__weak) id<FBOpenableAttachmentControllerDelegate> delegate; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)modalPresentationStackManager;
-(void)attachmentNodeWillLift:(id)arg1 ;
-(void)attachmentNodeDidUnlift:(id)arg1 ;
-(void)attachmentNodeMayOpen:(id)arg1 ;
-(void)attachmentNodeWillOpen:(id)arg1 animated:(BOOL)arg2 ;
-(void)attachmentNodeDidOpen:(id)arg1 ;
-(void)attachmentNodeMayClose:(id)arg1 ;
-(void)attachmentNodeWillClose:(id)arg1 animated:(BOOL)arg2 ;
-(void)attachmentNodeDidClose:(id)arg1 ;
-(id)existingModalLayerForAttachmentNode:(id)arg1 ;
-(BOOL)attachmentNode:(id)arg1 shouldBeginGesture:(id)arg2 ;
-(void)attachmentNode:(id)arg1 didUpdateInteractionProgress:(double)arg2 ;
-(id)attachmentNode;
-(BOOL)shouldAllowDismissGestureAtPoint:(CGPoint)arg1 inDirection:(long long)arg2 ;
@end

