/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:37 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSDictionary;

@interface FBPaymentsFormTextFieldViewDescriptor : FBValueObject <NSCopying> {

	BOOL _isOptional;
	NSString* _textFieldViewType;
	NSString* _accessibilityLabel;
	NSString* _placeholderString;
	NSString* _fieldIdentifier;
	NSString* _prefilledContent;
	NSDictionary* _extraData;

}

@property (nonatomic,copy,readonly) NSString * textFieldViewType;               //@synthesize textFieldViewType=_textFieldViewType - In the implementation block
@property (nonatomic,copy,readonly) NSString * accessibilityLabel;              //@synthesize accessibilityLabel=_accessibilityLabel - In the implementation block
@property (nonatomic,copy,readonly) NSString * placeholderString;               //@synthesize placeholderString=_placeholderString - In the implementation block
@property (nonatomic,copy,readonly) NSString * fieldIdentifier;                 //@synthesize fieldIdentifier=_fieldIdentifier - In the implementation block
@property (nonatomic,copy,readonly) NSString * prefilledContent;                //@synthesize prefilledContent=_prefilledContent - In the implementation block
@property (nonatomic,readonly) BOOL isOptional;                                 //@synthesize isOptional=_isOptional - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * extraData;                   //@synthesize extraData=_extraData - In the implementation block
-(id)initWithTextFieldViewType:(id)arg1 accessibilityLabel:(id)arg2 placeholderString:(id)arg3 fieldIdentifier:(id)arg4 prefilledContent:(id)arg5 isOptional:(BOOL)arg6 extraData:(id)arg7 ;
-(NSString *)textFieldViewType;
-(NSString *)prefilledContent;
-(BOOL)isOptional;
-(NSString *)accessibilityLabel;
-(NSString *)fieldIdentifier;
-(NSString *)placeholderString;
-(NSDictionary *)extraData;
@end

