/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:36 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBPaymentsPaymentMethodBankTableViewControllerDelegate.h>
#import <Messenger/FBPaymentsEventListener.h>
#import <Messenger/FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectAction.h>

@protocol FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectActionDelegate, FBPaymentsNavigationDelegate;
@class FBPaymentsPaymentMethodBankTableViewController, FBPaymentsEventListenerAnnouncer, NSString;

@interface FBPaymentsSelectPaymentMethodsNetBankingChooseBankAction : NSObject <FBPaymentsPaymentMethodBankTableViewControllerDelegate, FBPaymentsEventListener, FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectAction> {

	FBPaymentsPaymentMethodBankTableViewController* _bankViewController;
	FBPaymentsEventListenerAnnouncer* _eventAnnouncer;
	id<FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectActionDelegate> _delegate;
	id<FBPaymentsNavigationDelegate> _navigationDelegate;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<FBPaymentsNavigationDelegate> navigationDelegate;                                             //@synthesize navigationDelegate=_navigationDelegate - In the implementation block
@property (assign,nonatomic,__weak) id<FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectActionDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)announcerIdentifier;
-(void)didTriggerEventWithName:(id)arg1 announcerIdentifier:(id)arg2 collectedData:(id)arg3 ;
-(void)handleSelectActionForPaymentMethodOption:(id)arg1 withBillingCountryCode:(id)arg2 ;
-(void)paymentMethodBankTableViewController:(id)arg1 didSelectBank:(id)arg2 ;
-(id)init;
-(void)setDelegate:(id<FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectActionDelegate>)arg1 ;
-(id<FBPaymentsSelectPaymentMethodsPaymentMethodOptionSelectActionDelegate>)delegate;
-(id<FBPaymentsNavigationDelegate>)navigationDelegate;
-(void)addEventListener:(id)arg1 ;
-(void)removeEventListener:(id)arg1 ;
-(void)setNavigationDelegate:(id<FBPaymentsNavigationDelegate>)arg1 ;
@end

