/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:39 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <FBSharedFramework/FBGraphQLInput.h>

@class NSString, NSArray, NSNumber;

@interface FBProfileIntroCardSetData : FBGraphQLInput {

	NSString* _clientMutationId;
	NSString* _actorId;
	NSString* _bio;
	NSString* _publishBioFeedStory;
	NSArray* _photoIds;
	NSArray* _photoIdsToRemove;
	NSString* _discoverySessionReferrerType;
	NSString* _referrerId;
	NSNumber* _entityCardPosition;
	NSArray* _externalLinks;

}

@property (nonatomic,copy) NSString * clientMutationId;                          //@synthesize clientMutationId=_clientMutationId - In the implementation block
@property (nonatomic,copy) NSString * actorId;                                   //@synthesize actorId=_actorId - In the implementation block
@property (nonatomic,copy) NSString * bio;                                       //@synthesize bio=_bio - In the implementation block
@property (nonatomic,copy) NSString * publishBioFeedStory;                       //@synthesize publishBioFeedStory=_publishBioFeedStory - In the implementation block
@property (nonatomic,copy) NSArray * photoIds;                                   //@synthesize photoIds=_photoIds - In the implementation block
@property (nonatomic,copy) NSArray * photoIdsToRemove;                           //@synthesize photoIdsToRemove=_photoIdsToRemove - In the implementation block
@property (nonatomic,copy) NSString * discoverySessionReferrerType;              //@synthesize discoverySessionReferrerType=_discoverySessionReferrerType - In the implementation block
@property (nonatomic,copy) NSString * referrerId;                                //@synthesize referrerId=_referrerId - In the implementation block
@property (nonatomic,copy) NSNumber * entityCardPosition;                        //@synthesize entityCardPosition=_entityCardPosition - In the implementation block
@property (nonatomic,copy) NSArray * externalLinks;                              //@synthesize externalLinks=_externalLinks - In the implementation block
-(NSString *)referrerId;
-(void)setReferrerId:(NSString *)arg1 ;
-(NSNumber *)entityCardPosition;
-(void)setEntityCardPosition:(NSNumber *)arg1 ;
-(NSString *)publishBioFeedStory;
-(void)setPublishBioFeedStory:(NSString *)arg1 ;
-(NSArray *)photoIds;
-(void)setPhotoIds:(NSArray *)arg1 ;
-(NSArray *)photoIdsToRemove;
-(void)setPhotoIdsToRemove:(NSArray *)arg1 ;
-(NSString *)discoverySessionReferrerType;
-(void)setDiscoverySessionReferrerType:(NSString *)arg1 ;
-(NSArray *)externalLinks;
-(void)setExternalLinks:(NSArray *)arg1 ;
-(void)setActorId:(NSString *)arg1 ;
-(void)setClientMutationId:(NSString *)arg1 ;
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(NSString *)clientMutationId;
-(NSString *)actorId;
-(void)setBio:(NSString *)arg1 ;
-(NSString *)bio;
@end

