/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:39 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>
#import <Messenger/FBPullToRefreshViewDelegate.h>
#import <FBSharedFramework/FBComponentScrollEventListener.h>

@protocol FBStreamListViewDelegate;
@class FBAnimationPerformanceLogger, UIScrollView, FBPullToRefreshView, NSString;

@interface FBStreamListView : UIView <FBPullToRefreshViewDelegate, FBComponentScrollEventListener> {

	FBAnimationPerformanceLogger* _apTracker;
	BOOL _feedViewDelegateRespondToDidScroll;
	UIScrollView* _scrollView;
	FBPullToRefreshView* _pullToRefreshView;
	double _bottomScrollBuffer;
	double _topScrollBuffer;
	id<FBStreamListViewDelegate> _feedViewDelegate;

}

@property (nonatomic,readonly) UIScrollView * scrollView;                                       //@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,readonly) FBPullToRefreshView * pullToRefreshView;                         //@synthesize pullToRefreshView=_pullToRefreshView - In the implementation block
@property (nonatomic,readonly) double bottomScrollBuffer;                                       //@synthesize bottomScrollBuffer=_bottomScrollBuffer - In the implementation block
@property (nonatomic,readonly) double topScrollBuffer;                                          //@synthesize topScrollBuffer=_topScrollBuffer - In the implementation block
@property (assign,nonatomic,__weak) id<FBStreamListViewDelegate> feedViewDelegate;              //@synthesize feedViewDelegate=_feedViewDelegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)parentViewDidDisappear;
-(double)bottomScrollBuffer;
-(double)topScrollBuffer;
-(void)_cleanUpForLastConfig;
-(void)_layoutIfNotScrolling;
-(id<FBStreamListViewDelegate>)feedViewDelegate;
-(void)pullToRefreshViewDidTriggerRefresh:(id)arg1 ;
-(void)setFeedViewDelegate:(id<FBStreamListViewDelegate>)arg1 ;
-(void)updateBackgroundColor:(id)arg1 ;
-(void)updateHasPullToRefresh:(BOOL)arg1 ;
-(FBPullToRefreshView *)pullToRefreshView;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setBounds:(CGRect)arg1 ;
-(void)scrollViewDidScroll:(FBScrollViewState)arg1 ;
-(void)scrollViewWillBeginDragging:(FBScrollViewState)arg1 ;
-(void)scrollViewDidEndDragging:(FBScrollViewState)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(FBScrollViewState)arg1 ;
-(void)scrollViewDidScrollToTop:(FBScrollViewState)arg1 ;
-(id)tableView;
-(id)collectionView;
-(UIScrollView *)scrollView;
-(void)setConfiguration:(id)arg1 ;
-(void)_layout;
-(id)initWithConfiguration:(id)arg1 ;
-(BOOL)accessibilityScroll:(long long)arg1 ;
@end

