/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:38 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <FBSharedFramework/CKCompositeComponent.h>

@class FBMemFeedback, FBFeedToolbox, FBInlineVoiceSwitcherViewModel;

@interface FBUFIInlineVoiceSwitcherComponent : CKCompositeComponent {

	FBMemFeedback* _feedback;
	FBFeedToolbox* _toolbox;
	FBInlineVoiceSwitcherViewModel* _inlineVoiceSwitcherViewModel;

}

@property (nonatomic,readonly) FBMemFeedback * feedback;                                                   //@synthesize feedback=_feedback - In the implementation block
@property (nonatomic,readonly) FBFeedToolbox * toolbox;                                                    //@synthesize toolbox=_toolbox - In the implementation block
@property (nonatomic,readonly) FBInlineVoiceSwitcherViewModel * inlineVoiceSwitcherViewModel;              //@synthesize inlineVoiceSwitcherViewModel=_inlineVoiceSwitcherViewModel - In the implementation block
+(id)newWithFeedback:(id)arg1 profilePictureUri:(id)arg2 tapAction:(CKTypedComponentAction<>)arg3 inlineVoiceSwitcherViewModel:(id)arg4 toolbox:(id)arg5 ;
-(FBFeedToolbox *)toolbox;
-(FBInlineVoiceSwitcherViewModel *)inlineVoiceSwitcherViewModel;
-(FBMemFeedback *)feedback;
@end

