/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:43 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIGestureRecognizer.h>

@protocol FBVideoFilmstripScrubGestureRecognizerDelegate;
@interface FBVideoFilmstripScrubGestureRecognizer : UIGestureRecognizer {

	id<FBVideoFilmstripScrubGestureRecognizerDelegate> _scrubDelegate;

}

@property (assign,nonatomic,__weak) id<FBVideoFilmstripScrubGestureRecognizerDelegate> scrubDelegate;              //@synthesize scrubDelegate=_scrubDelegate - In the implementation block
-(id<FBVideoFilmstripScrubGestureRecognizerDelegate>)scrubDelegate;
-(void)setScrubDelegate:(id<FBVideoFilmstripScrubGestureRecognizerDelegate>)arg1 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
@end

