/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:35 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue, FBWebRTCCallLogPersistenceManagerDelegate;
@class NSString, NSObject;

@interface FBWebRTCCallLogPersistenceManager : NSObject {

	NSString* _callStatsDirectoryPath;
	NSObject*<OS_dispatch_queue> _callStatsQueue;
	unsigned long long _pendingCallSummariesDelays;
	id<FBWebRTCCallLogPersistenceManagerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBWebRTCCallLogPersistenceManagerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_sendPendingLogSummariesIfPossible;
-(id)_pathForCallId:(long long)arg1 ;
-(void)_sendPendingCallSummaries;
-(id)_statsDirectoryPath;
-(void)logPendingCallSummaries;
-(void)saveCallSummary:(id)arg1 forCallId:(long long)arg2 ;
-(void)deleteCallSummaryForCallId:(long long)arg1 ;
-(id)init;
-(void)setDelegate:(id<FBWebRTCCallLogPersistenceManagerDelegate>)arg1 ;
-(id<FBWebRTCCallLogPersistenceManagerDelegate>)delegate;
@end

