/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:42 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/IGSurfaceInputType.h>

@class EAGLContext, NSString;

@interface IGSurface : NSObject <IGSurfaceInputType> {

	unsigned _texture;
	unsigned _framebuffer;
	unsigned _renderbuffer;
	unsigned _internalFormat;
	unsigned _format;
	unsigned long long _planeIndex;
	BOOL _generatedTexture;
	CVOpenGLESTextureCacheRef _textureCache;
	CVBufferRef _cvTexture;
	EAGLContext* _glContext;
	CAEAGLLayer* _layer;
	CGSize _size;
	BOOL _layerRenderBufferStorageNeedsRefresh;
	unsigned char _flipped;
	unsigned _textureTarget;
	CVBufferRef _pixelBuffer;

}

@property (nonatomic,readonly) unsigned texture; 
@property (nonatomic,readonly) unsigned textureTarget;                              //@synthesize textureTarget=_textureTarget - In the implementation block
@property (nonatomic,readonly) unsigned framebuffer; 
@property (nonatomic,readonly) unsigned renderbuffer; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) CVBufferRef pixelBuffer;                             //@synthesize pixelBuffer=_pixelBuffer - In the implementation block
@property (nonatomic,readonly) CGSize size;                                         //@synthesize size=_size - In the implementation block
@property (getter=isFlipped,nonatomic,readonly) unsigned char flipped;              //@synthesize flipped=_flipped - In the implementation block
@property (nonatomic,readonly) BOOL isConsumable; 
-(BOOL)isConsumable;
-(id)initWithPixelBuffer:(CVBufferRef)arg1 textureInternalFormat:(int)arg2 textureFormat:(unsigned)arg3 planeIndex:(unsigned long long)arg4 ;
-(id)initWithIGTexture:(id)arg1 ;
-(id)initWithPixelBuffer:(CVBufferRef)arg1 ;
-(id)initWithTexture:(unsigned)arg1 target:(unsigned)arg2 size:(CGSize)arg3 ;
-(id)initWithFramebuffer:(unsigned)arg1 size:(CGSize)arg2 ;
-(CGSize)size;
-(void)dealloc;
-(id)initWithSize:(CGSize)arg1 ;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)present;
-(id)initWithLayer:(CAEAGLLayer*)arg1 ;
-(CVBufferRef)pixelBuffer;
-(unsigned)texture;
-(id)initWithTexture:(unsigned)arg1 size:(CGSize)arg2 ;
-(unsigned)textureTarget;
-(unsigned char)isFlipped;
-(unsigned)framebuffer;
-(unsigned)renderbuffer;
@end

