/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:34 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UICollectionViewCell.h>
#import <Messenger/MNFramedGroupPictureViewDelegate.h>
#import <Messenger/MNThreadCustomizationPromptViewDelegate.h>
#import <Messenger/MNAdminMessageConfirmFriendRequestViewDelegate.h>
#import <FBSharedFramework/FBClassProvidable.h>
#import <FBSharedFramework/MNCollectionViewLayoutAttributesTracking.h>

@protocol MNAdminMessageCollectionViewCellDelegate;
@class FBRichTextView, FBLazyCreator, MNAppMessageAttachmentUtils, MNAdminMessageCellLayout, MNThreadImageManager, FBImageDownloader, MNCDNProfileImageDownloader, MNAdminMessageContentExtractor, FBUserSession, FBMobileConfigContextManager, MNMessageRow, UICollectionViewLayoutAttributes, NSString;

@interface MNAdminMessageCollectionViewCell : UICollectionViewCell <MNFramedGroupPictureViewDelegate, MNThreadCustomizationPromptViewDelegate, MNAdminMessageConfirmFriendRequestViewDelegate, FBClassProvidable, MNCollectionViewLayoutAttributesTracking> {

	FBRichTextView* _label;
	FBLazyCreator* _groupPictureViewCreator;
	FBLazyCreator* _groupAddPhotoButtonCreator;
	FBLazyCreator* _threadCustomizationPromptViewCreator;
	FBLazyCreator* _journeySetupViewCreator;
	FBLazyCreator* _confirmFriendRequestViewCreator;
	MNAppMessageAttachmentUtils* _attachmentUtils;
	MNAdminMessageCellLayout* _cellLayout;
	MNThreadImageManager* _imageManager;
	FBImageDownloader* _imageDownloader;
	MNCDNProfileImageDownloader* _cdnImageDownloader;
	MNAdminMessageContentExtractor* _contentExtractor;
	FBUserSession* _session;
	FBMobileConfigContextManager* _configManager;
	id<MNAdminMessageCollectionViewCellDelegate> _delegate;
	MNMessageRow* _messageRow;
	UICollectionViewLayoutAttributes* _layoutAttributes;

}

@property (nonatomic,copy) UICollectionViewLayoutAttributes * layoutAttributes;                         //@synthesize layoutAttributes=_layoutAttributes - In the implementation block
@property (assign,nonatomic,__weak) id<MNAdminMessageCollectionViewCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) MNMessageRow * messageRow;                                                 //@synthesize messageRow=_messageRow - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didTapGroupAddPhotoButton;
-(id)initWithAttachmentUtils:(id)arg1 messageCellLayout:(id)arg2 threadImageManager:(id)arg3 imageDownloader:(id)arg4 cdnImageDownloader:(id)arg5 contentExtractor:(id)arg6 session:(id)arg7 configManager:(id)arg8 ;
-(void)_prepareMessageReset;
-(void)_setPromptMessage;
-(void)_setConfirmFriendRequestMessage;
-(void)_setJourneySetupMessage;
-(void)_setGeneralAdminMessage;
-(void)_downloadImageWithURL:(id)arg1 successBlock:(/*^block*/id)arg2 ;
-(void)_downloadProfileImageWithFbid:(id)arg1 size:(unsigned long long)arg2 successBlock:(/*^block*/id)arg3 ;
-(void)_addImageForGroupPictureView:(id)arg1 ;
-(BOOL)_showsAddPhotoButton;
-(id)_photoViewModelForMessage:(id)arg1 ;
-(void)framedGroupPictureViewDidPerformTap:(id)arg1 ;
-(void)threadCustomizationPromptView:(id)arg1 didSelectItem:(id)arg2 ;
-(void)threadCustomizationPromptView:(id)arg1 didDeselectItem:(id)arg2 ;
-(void)adminMessageConfirmFriendRequestView:(id)arg1 didTapActionButtonType:(long long)arg2 ;
-(void)adminMessageConfirmFriendRequestView:(id)arg1 didSelectGreeting:(id)arg2 ;
-(void)adminMessageConfirmFriendRequestView:(id)arg1 didUpdateViewState:(long long)arg2 ;
-(id)initWithProviderMapData:(id)arg1 ;
-(MNMessageRow *)messageRow;
-(void)setMessageRow:(MNMessageRow *)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<MNAdminMessageCollectionViewCellDelegate>)arg1 ;
-(void)dealloc;
-(id<MNAdminMessageCollectionViewCellDelegate>)delegate;
-(void)applyLayoutAttributes:(id)arg1 ;
-(void)setLayoutAttributes:(UICollectionViewLayoutAttributes *)arg1 ;
-(UICollectionViewLayoutAttributes *)layoutAttributes;
@end

