/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:36 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class MNPSAppointmentCreateDatePickerView, UILabel;

@interface MNBookingRequestsAdminRequestCreationDatePickerView : UIView {

	MNPSAppointmentCreateDatePickerView* _startDatePickerView;
	MNPSAppointmentCreateDatePickerView* _startTimePickerView;
	UILabel* _endTimeLabel;
	MNPSAppointmentCreateDatePickerView* _endTimePickerView;

}
-(void)fb_addStartDatePickerViewWithDelegate:(id)arg1 ;
-(void)fb_addStartTimePickerViewWithDelegate:(id)arg1 ;
-(void)fb_addEndTimeLabel;
-(void)fb_addEndTimePickerViewWithDelegate:(id)arg1 ;
-(void)fb_tapGesture:(id)arg1 ;
-(id)startDatePickerView;
-(id)startTimePickerView;
-(id)endTimeLabel;
-(id)endTimePickerView;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)initWithFrame:(CGRect)arg1 delegate:(id)arg2 ;
@end

