/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:33 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSArray, NSString;

@interface MNBotMenuViewModel : FBValueObject <NSCopying, NSCoding> {

	BOOL _isInputFieldHidden;
	BOOL _isNavigationBarHidden;
	NSArray* _ctaViewModels;
	NSString* _navigationBarTitle;

}

@property (nonatomic,copy,readonly) NSArray * ctaViewModels;                    //@synthesize ctaViewModels=_ctaViewModels - In the implementation block
@property (nonatomic,readonly) BOOL isInputFieldHidden;                         //@synthesize isInputFieldHidden=_isInputFieldHidden - In the implementation block
@property (nonatomic,readonly) BOOL isNavigationBarHidden;                      //@synthesize isNavigationBarHidden=_isNavigationBarHidden - In the implementation block
@property (nonatomic,copy,readonly) NSString * navigationBarTitle;              //@synthesize navigationBarTitle=_navigationBarTitle - In the implementation block
-(id)initWithCtaViewModels:(id)arg1 isInputFieldHidden:(BOOL)arg2 isNavigationBarHidden:(BOOL)arg3 navigationBarTitle:(id)arg4 ;
-(NSArray *)ctaViewModels;
-(BOOL)isInputFieldHidden;
-(BOOL)isNavigationBarHidden;
-(NSString *)navigationBarTitle;
@end

