/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:33 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBBackgroundFetchObserver.h>
#import <FBSharedFramework/FBViewerContextClassProvidable.h>
#import <FBSharedFramework/MNServiceControllable.h>

@protocol OS_dispatch_queue;
@class MNCalendarStore, NSObject, NSString;

@interface MNCalendarSyncService : NSObject <FBBackgroundFetchObserver, FBViewerContextClassProvidable, MNServiceControllable> {

	MNCalendarStore* _calendarStore;
	NSObject*<OS_dispatch_queue> _calendarSyncQueue;
	id _foregroundNotificationObserver;
	id _backgroundFetchObserver;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithCalendarStore:(id)arg1 ;
-(id)initWithProviderMapData:(id)arg1 ;
-(void)handleIdle;
-(void)handleBackgroundFetchRequest:(id)arg1 ;
-(void)_didEnterForeground;
-(void)stop;
-(void)_setUp;
-(void)_tearDown;
-(void)start:(id)arg1 ;
@end

