/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:41 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBGenericMultiFetcher, MNInboxFetchConfig;

@interface MNInboxDiscoverySurfaceFetcher : NSObject {

	FBGenericMultiFetcher* _multiFetcher;
	MNInboxFetchConfig* _fetchConfig;

}
-(id)initWithSession:(id)arg1 fetchConfig:(id)arg2 ;
-(BOOL)isFetchingWithFetchID:(id)arg1 ;
-(void)cancelFetchingWithFetchID:(id)arg1 ;
-(id)fetchWithServiceName:(id)arg1 categoryID:(id)arg2 successBlock:(/*^block*/id)arg3 failureBlock:(/*^block*/id)arg4 ;
@end

