/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:33 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNOmniMNuxViewControllerDelegate.h>
#import <FBSharedFramework/FBClassProvidable.h>

@protocol FBProvider, MNModalPresentation;
@class MNOmniMNuxViewController, MNOmniMSettingsViewController, MNOmniMSettingsStore, MNMessageTextDataDetector, MNSaveMessageHandler, FBMobileConfigContextManager, NSString;

@interface MNMAISuggestionsHandler : NSObject <MNOmniMNuxViewControllerDelegate, FBClassProvidable> {

	id<FBProvider> _textHandlerProvider;
	id<FBProvider> _locationHandlerProvider;
	id<FBProvider> _stickerHandlerProvider;
	id<FBProvider> _rideHandlerProvider;
	id<FBProvider> _paymentHandlerProvider;
	id<FBProvider> _reminderHandlerProvider;
	id<FBProvider> _pollHandlerProvider;
	id<FBProvider> _openAppHandlerProvider;
	id<FBProvider> _liveLocationHandlerProvider;
	id<FBProvider> _liveVideoHandlerProvider;
	id _currentHandler;
	MNOmniMNuxViewController* _nuxViewController;
	MNOmniMSettingsViewController* _settingsViewController;
	id<MNModalPresentation> _modalPresenter;
	/*^block*/id _nuxCompletionBlock;
	MNOmniMSettingsStore* _omniMSettingsStore;
	MNMessageTextDataDetector* _textDataDetector;
	MNSaveMessageHandler* _saveMessageHandler;
	FBMobileConfigContextManager* _configManager;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didCloseSettingsView;
-(void)handleSuggestion:(id)arg1 forThreadViewModel:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_handleText:(id)arg1 forThreadKey:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_handleSticker:(unsigned long long)arg1 forThreadKey:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_handleLocationWithLatitude:(double)arg1 longitude:(double)arg2 isCurrentLocation:(BOOL)arg3 forThreadKey:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)_handleRideWithProviderName:(id)arg1 destinationAddress:(id)arg2 destinationLocation:(id)arg3 forThreadKey:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)_handlePaymentWithAmountInCents:(id)arg1 currencyCode:(id)arg2 paymentType:(unsigned long long)arg3 forThreadKey:(id)arg4 otherUsers:(id)arg5 themeColor:(id)arg6 completion:(/*^block*/id)arg7 ;
-(void)_handleReminderWithDate:(id)arg1 messageId:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_handlePollWithOptions:(id)arg1 questionText:(id)arg2 allUsers:(id)arg3 themeColor:(id)arg4 forThreadKey:(id)arg5 completion:(/*^block*/id)arg6 ;
-(void)_handleScheduleCallWithDate:(id)arg1 messageId:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_handleOpenAppForURL:(id)arg1 withTitle:(id)arg2 forThreadKey:(id)arg3 withSuggestionId:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)_handleNuxWithCompletion:(/*^block*/id)arg1 ;
-(void)_handleLiveLocationWithCompletion:(/*^block*/id)arg1 ;
-(void)_handleRTCCallWithThreadKey:(id)arg1 users:(id)arg2 isVideoCall:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)_handleSaveWithThreadKey:(id)arg1 threadViewModel:(id)arg2 messageId:(id)arg3 completion:(/*^block*/id)arg4 ;
-(long long)_maxMessagesToAnalyze;
-(void)omniMNuxViewControllerDidDismiss:(id)arg1 ;
-(void)omniMNuxViewControllerDidSelectSettings:(id)arg1 ;
-(id)initWithProviderMapData:(id)arg1 ;
@end

