/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:34 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@protocol MNMessageReactionsDetailHeaderViewDelegate;
@class UIView, UIButton, MNMessageReactionsDetailViewModel, NSArray, UIScrollView;

@interface MNMessageReactionsDetailHeaderView : UIView {

	UIView* _pageIndicator;
	UIButton* _allReactionsButton;
	UIView* _separatorView;
	MNMessageReactionsDetailViewModel* _viewModel;
	NSArray* _reactionViews;
	double _pageIndicatorProgress;
	UIScrollView* _containerScrollView;
	UIView* _leftIndicatorMaskView;
	UIView* _rightIndicatorMaskView;
	id<MNMessageReactionsDetailHeaderViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNMessageReactionsDetailHeaderViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_didTapAllReactionsButton;
-(void)_layoutPageIndicatorView;
-(void)_didTapReaction:(id)arg1 ;
-(CGRect)_pageIndicatorFrameForIndex:(unsigned long long)arg1 ;
-(void)setPageIndicatorProgress:(double)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<MNMessageReactionsDetailHeaderViewDelegate>)arg1 ;
-(void)dealloc;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<MNMessageReactionsDetailHeaderViewDelegate>)delegate;
-(void)setViewModel:(id)arg1 ;
@end

