/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:39 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class FBNetworkImageView, UILabel, UIView, UIImageView, MNNearbyPlaceCellViewModel;

@interface MNNearbyPlaceCell : UITableViewCell {

	FBNetworkImageView* _thumbnailImageView;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIView* _separatorView;
	UIImageView* _thumbnailMaskImageView;
	MNNearbyPlaceCellViewModel* _viewModel;

}
-(id)initWithReuseIdentifier:(id)arg1 imageDownloader:(id)arg2 ;
-(void)configureCellWithViewModel:(id)arg1 ;
-(void)layoutSubviews;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_updateBackgroundColor;
@end

