/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:36 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class UIView;

@interface MNPhotoEditingTabContainerView : UIView {

	UIView* _backgroundView;
	UIView* _composeTabBar;
	UIView* _topSeparatorView;

}
-(id)_separatorView;
-(void)_layoutSeparatorViews;
-(void)_initBackgroundView;
-(void)_initSeparatorViews;
-(void)_layoutTabBar;
-(id)initWithComposeTabBar:(id)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)_layoutBackgroundView;
@end

