/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:40 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Messenger/Messenger-Structs.h>
@class NSString, NSURL;

@interface MNRichShareBuilder : NSObject {

	NSString* _title;
	NSString* _body;
	NSString* _attribution;
	NSURL* _imageURL;
	NSString* _href;
	NSURL* _deepLinkURL;
	NSURL* _attributionDeepLinkURL;
	CGSize _imageSize;
	BOOL _shouldUseLargeModes;

}
+(id)richShare;
+(id)richShareFromExistingRichShare:(id)arg1 ;
-(id)withBody:(id)arg1 ;
-(id)withImageURL:(id)arg1 ;
-(id)withImageSize:(CGSize)arg1 ;
-(id)withShouldUseLargeModes:(BOOL)arg1 ;
-(id)withHref:(id)arg1 ;
-(id)withDeepLinkURL:(id)arg1 ;
-(id)withAttribution:(id)arg1 ;
-(id)withAttributionDeepLinkURL:(id)arg1 ;
-(id)withTitle:(id)arg1 ;
-(id)build;
@end

