/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:32 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Messenger/MNThreadBottomBannerViewDelegate.h>
#import <FBSharedFramework/FBClassProvidable.h>

@protocol MNSecureThreadBottomBannerViewControllerDelegate;
@class MNThreadBottomBannerView, NSString;

@interface MNSecureThreadBottomBannerViewController : UIViewController <MNThreadBottomBannerViewDelegate, FBClassProvidable> {

	MNThreadBottomBannerView* _secureThreadBottomBannerView;
	id<MNSecureThreadBottomBannerViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNSecureThreadBottomBannerViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)threadBottomBannerView:(id)arg1 didTouchTextCheckingResult:(id)arg2 ;
-(id)initWithProviderMapData:(id)arg1 ;
-(void)setDelegate:(id<MNSecureThreadBottomBannerViewControllerDelegate>)arg1 ;
-(id<MNSecureThreadBottomBannerViewControllerDelegate>)delegate;
-(void)loadView;
@end

