/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:33 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNSyncProtocolQueueConfigurationListening.h>
#import <FBSharedFramework/MNSPDataStoreListening.h>

@class MNCrossProcessDiskCommunicationAdapterService, NSString;

@interface MNSyncProtocolSettingsSerializer : NSObject <MNSyncProtocolQueueConfigurationListening, MNSPDataStoreListening> {

	MNCrossProcessDiskCommunicationAdapterService* _diskCommunicationAdapterService;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)didConfigureSyncProtocolQueueWithType:(id)arg1 apiVersion:(id)arg2 queueParams:(id)arg3 entityFbId:(id)arg4 ;
-(id)initWithDiskCommunicationService:(id)arg1 ;
-(void)didInvalidateStore;
-(void)didUpdateSequenceId:(long long)arg1 withToken:(id)arg2 ;
@end

