/*
* This header is generated by classdump-dyld 1.0
* on Saturday, March 18, 2017 at 1:27:35 PM Central European Standard Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/982F7718-F913-4C3D-AECC-191FDA119619/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNTypingNotificationManagerDelegate.h>
#import <FBSharedFramework/FBClassProvidable.h>
#import <Messenger/MNThreadViewModelConfigurable.h>
#import <Messenger/FBMMessageSendListening.h>
#import <FBSharedFramework/MNThreadSummarySubscribing.h>
#import <FBSharedFramework/MNSecureThreadSubscribing.h>

@protocol MNAuthenticationManager;
@class MNSoundController, FBMDeliveryReceiptGating, FBMMessageSendStatesGating, MNTypingNotificationManager, FBMLocalThreadMessagesQuerier, NSMutableSet, MNThreadViewModel, NSString;

@interface MNThreadSoundPlayer : NSObject <MNTypingNotificationManagerDelegate, FBClassProvidable, MNThreadViewModelConfigurable, FBMMessageSendListening, MNThreadSummarySubscribing, MNSecureThreadSubscribing> {

	MNSoundController* _soundController;
	id<MNAuthenticationManager> _authManager;
	FBMDeliveryReceiptGating* _deliveryReceiptGating;
	FBMMessageSendStatesGating* _sendStatesGating;
	MNTypingNotificationManager* _typingManager;
	FBMLocalThreadMessagesQuerier* _threadMessagesQuerier;
	BOOL _isObserving;
	NSMutableSet* _sentMessageSet;
	BOOL _enabled;
	MNThreadViewModel* _threadViewModel;

}

@property (nonatomic,retain) MNThreadViewModel * threadViewModel;              //@synthesize threadViewModel=_threadViewModel - In the implementation block
@property (assign,nonatomic) BOOL enabled;                                     //@synthesize enabled=_enabled - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_stopObservers;
-(void)_startObservers;
-(void)configureThreadViewModelDependenciesWith:(id)arg1 ;
-(void)tearDownThreadViewModelDependencies;
-(MNThreadViewModel *)threadViewModel;
-(void)didEnqueueMessage:(id)arg1 ;
-(void)didFailMessage:(id)arg1 error:(id)arg2 ;
-(void)willRetryMessage:(id)arg1 ;
-(void)message:(id)arg1 didUpdateUploadProgress:(double)arg2 ;
-(void)setThreadViewModel:(MNThreadViewModel *)arg1 ;
-(void)didApplyUpdate:(id)arg1 toSecureThreadWithKey:(id)arg2 ;
-(void)didUpdateAllSecureThreads;
-(void)_updateObservation;
-(void)_inviteBannerDidAppear:(id)arg1 ;
-(void)_inviteBannerDidDismiss:(id)arg1 ;
-(void)_playSoundForReadReceiptInSummary:(id)arg1 ;
-(void)didUpdateTypingState;
-(id)initWithProviderMapData:(id)arg1 ;
-(void)didApplyUpdates:(id)arg1 toThreadSummary:(id)arg2 ;
-(void)didDeleteThreadWithKey:(id)arg1 ;
-(void)didReplaceThreadSummary:(id)arg1 withThreadSummary:(id)arg2 forThreadKey:(id)arg3 ;
-(void)didPurgeSummary:(id)arg1 ;
-(void)didPurgeAllThreadSummaries;
-(void)didPutMessageBackInQueue:(id)arg1 ;
-(void)didPublishMessage:(id)arg1 ;
-(void)didSendMessage:(id)arg1 ;
-(void)didCancelMessage:(id)arg1 ;
-(BOOL)enabled;
-(void)dealloc;
-(void)setEnabled:(BOOL)arg1 ;
@end

