/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class EGODatabase, EGODatabaseStatement, NSSet, NSError;

@interface FBMessagingPruneThreadsOperation : NSOperation {

	EGODatabase* _db;
	EGODatabaseStatement* _selectOldThreadsStatement;
	EGODatabaseStatement* _deleteOldThreadsStatement;
	EGODatabaseStatement* _deleteOrphanedMessagesStatement;
	EGODatabaseStatement* _deleteOrphanedExtensibleMessagePropsStatement;
	NSSet* _prunedThreadKeys;
	NSError* _error;

}

@property (nonatomic,copy,readonly) NSSet * prunedThreadKeys;              //@synthesize prunedThreadKeys=_prunedThreadKeys - In the implementation block
@property (nonatomic,copy,readonly) NSError * error;                       //@synthesize error=_error - In the implementation block
-(void)_pruneThreadsAndAssociatedDataIfNecessary;
-(void)_pruneThreadsAndAssociatedData:(id)arg1 ;
-(id)initWithDB:(id)arg1 selectOldThreadsStatement:(id)arg2 deleteOldThreadsStatement:(id)arg3 deleteOrphanedMessagesStatement:(id)arg4 deleteOrphanedExtensibleMessagePropsStatement:(id)arg5 ;
-(NSSet *)prunedThreadKeys;
-(void)main;
-(NSError *)error;
@end

