/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:51 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface FBMThreadMuteSettingsUpdate : NSObject <NSCoding, NSCopying> {

	unsigned long long _subtype;
	long long _messageNotifications_mutedUntil;
	unsigned long long _mentions_mentionMuteSetting;
	unsigned long long _reactions_reactionMuteSetting;

}
+(id)messageNotificationsWithMutedUntil:(long long)arg1 ;
+(id)reactionsWithReactionMuteSetting:(unsigned long long)arg1 ;
+(id)mentionsWithMentionMuteSetting:(unsigned long long)arg1 ;
-(void)matchMessageNotifications:(/*^block*/id)arg1 mentions:(/*^block*/id)arg2 reactions:(/*^block*/id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

