/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableDictionary;

@interface FBParticleEmitterShader : NSObject {

	NSMutableDictionary* _attributes;
	NSMutableDictionary* _uniforms;
	int _program;

}

@property (assign,nonatomic) int program;              //@synthesize program=_program - In the implementation block
+(id)vertexShaderString;
+(id)fragmentShaderString;
+(id)_readShaderString:(id)arg1 extension:(id)arg2 ;
-(int)attribute:(id)arg1 ;
-(int)uniform:(id)arg1 ;
-(unsigned)bindTexture:(id)arg1 toLocation:(int)arg2 ;
-(void)enableAttributes;
-(void)disableAttributes;
-(id)init;
-(void)setProgram:(int)arg1 ;
-(int)program;
-(void)loadShader;
@end

