/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBUserSession;

@interface FBVideoPlayerItemExpirationHelper : NSObject {

	FBUserSession* _session;

}
-(BOOL)urlIsExpired:(id)arg1 ;
-(void)updateVideoPlaybackItem:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(BOOL)_urlIsExpired:(id)arg1 ;
-(void)_runGraphQLQueryForVideo:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(id)_getOEParam:(id)arg1 ;
-(void)updateVideoPlayerItem:(id)arg1 withCompletion:(/*^block*/id)arg2 ;
-(id)initWithSession:(id)arg1 ;
@end

