/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:46 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface MNAttachmentShareTextViewModel : FBValueObject <NSCopying> {

	NSString* _title;
	NSString* _body;
	NSString* _attribution;

}

@property (nonatomic,copy,readonly) NSString * title;                    //@synthesize title=_title - In the implementation block
@property (nonatomic,copy,readonly) NSString * body;                     //@synthesize body=_body - In the implementation block
@property (nonatomic,copy,readonly) NSString * attribution;              //@synthesize attribution=_attribution - In the implementation block
-(id)initWithTitle:(id)arg1 body:(id)arg2 attribution:(id)arg3 ;
-(NSString *)title;
-(NSString *)body;
-(NSString *)attribution;
@end

