/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSDictionary, NSSet;

@interface MNBatchThreadSummaryResponse : FBValueObject <NSCopying> {

	NSDictionary* _threadQueryToThreadSummaryMap;
	NSSet* _threadQueriesWhoseThreadsDoNotExist;

}

@property (nonatomic,copy,readonly) NSDictionary * threadQueryToThreadSummaryMap;              //@synthesize threadQueryToThreadSummaryMap=_threadQueryToThreadSummaryMap - In the implementation block
@property (nonatomic,copy,readonly) NSSet * threadQueriesWhoseThreadsDoNotExist;               //@synthesize threadQueriesWhoseThreadsDoNotExist=_threadQueriesWhoseThreadsDoNotExist - In the implementation block
-(NSDictionary *)threadQueryToThreadSummaryMap;
-(id)initWithThreadQueryToThreadSummaryMap:(id)arg1 threadQueriesWhoseThreadsDoNotExist:(id)arg2 ;
-(NSSet *)threadQueriesWhoseThreadsDoNotExist;
@end

