/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNExtensionThreadDataPreparing.h>

@protocol OS_dispatch_queue;
@class MNExtensionThreadDataPreparingBehaviorCaller, MNMessagingAndUserDataPreparerRequestRunner, MNMessagingAndUserDataPreparerStateMachine, NSObject, NSString;

@interface MNExtensionThreadDataPreparer : NSObject <MNExtensionThreadDataPreparing> {

	MNExtensionThreadDataPreparingBehaviorCaller* _behaviorCaller;
	MNMessagingAndUserDataPreparerRequestRunner* _requestRunner;
	MNMessagingAndUserDataPreparerStateMachine* _stateMachine;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithAuthenticationManager:(id)arg1 threadImageManager:(id)arg2 attachmentUtils:(id)arg3 threadStore:(id)arg4 userStore:(id)arg5 messageSendQuerier:(id)arg6 globalDeleteMessageStoreReader:(id)arg7 apnsMessageStore:(id)arg8 ephemeralMessageStatusCalculator:(id)arg9 messageOptimisticUpdateApplier:(id)arg10 analytics:(id)arg11 queue:(id)arg12 ;
-(id)prepareExtensionThreadDataForSyncedThreadKey:(id)arg1 numberOfMessages:(long long)arg2 successBlock:(/*^block*/id)arg3 failureBlock:(/*^block*/id)arg4 ;
-(void)_canceledRequestWithId:(unsigned long long)arg1 ;
@end

