/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class FBAnalytics, NSObject, NSMutableDictionary;

@interface MNMessagesSyncDeltaProcessingTimeLogger : NSObject {

	FBAnalytics* _analytics;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableDictionary* _sequenceIdToBeginTimestamp;

}
-(id)initWithAnalytics:(id)arg1 queue:(id)arg2 ;
-(void)beginTrackingProcessingTimeForDeltasWithMetadatas:(id)arg1 ;
-(void)markDeltaWithMetadataProcessed:(id)arg1 ;
@end

