/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:31 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class UIView, MNMediaTrayEmptyCameraRollView, MNLoadingView, UICollectionView;

@interface MNMediaGridView : UIView {

	UIView* _selectedAssetsView;
	MNMediaTrayEmptyCameraRollView* _emptyAlbumView;
	long long _viewState;
	MNLoadingView* _loadingView;
	UICollectionView* _collectionView;

}

@property (nonatomic,retain) UICollectionView * collectionView;              //@synthesize collectionView=_collectionView - In the implementation block
-(CGRect)_viewPortRect;
-(id)_viewsForViewState:(long long)arg1 ;
-(void)_initializeEmptyAlbumViewIfNeeded;
-(id)initWithSelectedAssetsView:(id)arg1 ;
-(double)heightForSelectedAssetsView;
-(void)setSelectedAssetsViewHidden:(BOOL)arg1 ;
-(id)_viewsForCurrentViewState;
-(void)setViewState:(long long)arg1 ;
-(void)layoutSubviews;
-(UICollectionView *)collectionView;
-(void)setCollectionView:(UICollectionView *)arg1 ;
@end

