/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:33 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSURL, NSAttributedString;

@interface MNPaymentsTransferReceiptItemViewModel : FBValueObject <NSCopying> {

	NSURL* _imageURL;
	NSAttributedString* _titleAttributedString;
	NSAttributedString* _subtitleAttributedString;

}

@property (nonatomic,copy,readonly) NSURL * imageURL;                                           //@synthesize imageURL=_imageURL - In the implementation block
@property (nonatomic,copy,readonly) NSAttributedString * titleAttributedString;                 //@synthesize titleAttributedString=_titleAttributedString - In the implementation block
@property (nonatomic,copy,readonly) NSAttributedString * subtitleAttributedString;              //@synthesize subtitleAttributedString=_subtitleAttributedString - In the implementation block
-(id)initWithImageURL:(id)arg1 titleAttributedString:(id)arg2 subtitleAttributedString:(id)arg3 ;
-(NSAttributedString *)subtitleAttributedString;
-(NSAttributedString *)titleAttributedString;
-(NSURL *)imageURL;
@end

