/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:35 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNPhotoViewImageDownloadControlling <NSObject>
@required
-(void)clearPhotoView:(id)arg1;
-(id)configurePhotoView:(id)arg1 withPhotoViewModel:(id)arg2 size:(int)arg3 imageFlags:(unsigned long long)arg4 animated:(BOOL)arg5 keepCurrentImage:(BOOL)arg6 skipMiniPreview:(BOOL)arg7 analyticsTags:(id)arg8 callbackQueue:(id)arg9 successBlock:(/*^block*/id)arg10 failureBlock:(/*^block*/id)arg11;
-(id)configurePhotoView:(id)arg1 withPhotoViewModel:(id)arg2 size:(int)arg3 animated:(BOOL)arg4 analyticsTags:(id)arg5;

@end

