/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIControl.h>

@protocol MNProfServicesBookingBannerViewDelegate;
@class NSString, UILabel, UIImageView, NSArray, FBProfServicesBookingDataModel;

@interface MNProfServicesBookingSharedBannerView : UIControl {

	unsigned long long _count;
	NSString* _userName;
	UILabel* _bannerViewLabel;
	UIImageView* _reminderIcon;
	id<MNProfServicesBookingBannerViewDelegate> _delegate;
	NSArray* _bookingStatus;
	UILabel* _statusLabel;
	long long _banneViewType;
	FBProfServicesBookingDataModel* _viewModel;
	BOOL _actsAsPageAdmin;
	BOOL _isMixedRequestPendingState;

}
-(void)configureWithCount:(unsigned long long)arg1 bookingStatus:(id)arg2 userName:(id)arg3 viewModel:(id)arg4 bannerViewType:(long long)arg5 actsAsPageAdmin:(BOOL)arg6 isMixedRequestPendingState:(BOOL)arg7 ;
-(void)_tappedBannerview;
-(id)_reminderIcon;
-(void)_handleTappedAdminBannerView;
-(void)_handleTappedCunsumerBannerView;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)initWithDelegate:(id)arg1 ;
@end

