/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNSecureMessagingSendHandlingDelegate.h>

@protocol MNSecureMessageSendListening, MNSecureMessagingRegistrationStateUpdating, MNSecureMessagingSingleDeviceCryptoStateStoring, OS_dispatch_queue;
@class MNSecureMessagingStore, MNSecureThreadUpdater, MNSecureMessagingRemoteIdentityValidator, MNSecureMessagingParticipantListUpdateProcessor, NSObject;

@interface MNSecureMessagingSendResponseHandler : NSObject <MNSecureMessagingSendHandlingDelegate> {

	MNSecureMessagingStore* _store;
	MNSecureThreadUpdater* _threadUpdater;
	id<MNSecureMessageSendListening> _sendListener;
	id<MNSecureMessagingRegistrationStateUpdating> _deviceStatusUpdater;
	MNSecureMessagingRemoteIdentityValidator* _identityValidator;
	id<MNSecureMessagingSingleDeviceCryptoStateStoring> _cryptoStateStore;
	MNSecureMessagingParticipantListUpdateProcessor* _participantUpdateProcessor;
	NSObject*<OS_dispatch_queue> _queue;

}
-(BOOL)processSendResult:(id)arg1 withServerTimestamp:(unsigned long long)arg2 forPacketWithId:(id)arg3 ;
-(void)_handleSuccessForPackeId:(id)arg1 serverTimestamp:(unsigned long long)arg2 serverSignature:(id)arg3 ;
-(void)_handleSenderNotPrimaryForPacketId:(id)arg1 ;
-(void)_handleRecipientWithId:(id)arg1 notPrimaryWithNewIdentityKey:(id)arg2 packetId:(id)arg3 serverTimestamp:(unsigned long long)arg4 ;
-(BOOL)_handleParticipantListChanged:(id)arg1 timestamp:(unsigned long long)arg2 forPacketId:(id)arg3 ;
-(void)_handleUnknownError:(unsigned)arg1 forPacketId:(id)arg2 ;
-(id)initWithStore:(id)arg1 threadUpdater:(id)arg2 sendListener:(id)arg3 deviceStatusUpdater:(id)arg4 identityValidator:(id)arg5 cryptoStateStore:(id)arg6 participantUpdateProcessor:(id)arg7 queue:(id)arg8 ;
@end

