/*
* This header is generated by classdump-dyld 1.0
* on Sunday, December 18, 2016 at 3:09:50 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/D90B4FBB-2659-42DA-B3C0-734CC32E6C6C/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UISwitch.h>

@interface RCTSwitch : UISwitch {

	BOOL _wasOn;
	/*^block*/id _onChange;

}

@property (assign,nonatomic) BOOL wasOn;              //@synthesize wasOn=_wasOn - In the implementation block
@property (nonatomic,copy) id onChange;               //@synthesize onChange=_onChange - In the implementation block
-(id)onChange;
-(void)setOnChange:(id)arg1 ;
-(BOOL)wasOn;
-(void)setWasOn:(BOOL)arg1 ;
-(void)setOn:(BOOL)arg1 animated:(BOOL)arg2 ;
@end

