/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:33 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIView, UILabel;

@interface _FBTableViewSectionHeaderView : UITableViewHeaderFooterView {

	UIView* _cellSeparatorView;
	UIView* _sectionSeparatorView;
	BOOL _shouldHideSectionSeparator;
	UILabel* _labelView;
	long long _style;
	double _labelViewPadding;

}

@property (nonatomic,readonly) UILabel * labelView;                        //@synthesize labelView=_labelView - In the implementation block
@property (assign,nonatomic) long long style;                              //@synthesize style=_style - In the implementation block
@property (assign,nonatomic) double labelViewPadding;                      //@synthesize labelViewPadding=_labelViewPadding - In the implementation block
@property (assign,nonatomic) BOOL shouldHideSectionSeparator;              //@synthesize shouldHideSectionSeparator=_shouldHideSectionSeparator - In the implementation block
+(double)sidePaddingForStyle:(long long)arg1 ;
+(void)initialize;
-(void)setShouldHideSectionSeparator:(BOOL)arg1 ;
-(void)setLabelViewPadding:(double)arg1 ;
-(void)configureForStyle;
-(double)labelViewPadding;
-(BOOL)shouldHideSectionSeparator;
-(void)layoutSubviews;
-(long long)style;
-(void)setStyle:(long long)arg1 ;
-(id)initWithReuseIdentifier:(id)arg1 ;
-(UILabel *)labelView;
@end

