/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface FBAppBridgeTypeToJSONConverter : NSObject {

	NSMutableArray* _createdPasteboardNames;

}

@property (nonatomic,retain) NSMutableArray * createdPasteboardNames;              //@synthesize createdPasteboardNames=_createdPasteboardNames - In the implementation block
+(id)appBridgeTypeFromJSON:(id)arg1 ;
-(id)dictionaryWithAppBridgeTypesFromJSONDictionary:(id)arg1 ;
-(void)setCreatedPasteboardNames:(NSMutableArray *)arg1 ;
-(NSMutableArray *)createdPasteboardNames;
-(id)jsonDictionaryFromDictionaryWithAppBridgeTypes:(id)arg1 ;
-(id)convertedDictionaryFromDictionary:(id)arg1 convertingToJSON:(BOOL)arg2 ;
-(id)convertedArrayFromArray:(id)arg1 convertingToJSON:(BOOL)arg2 ;
-(id)jsonFromData:(id)arg1 tag:(id)arg2 ;
-(id)convertedObjectFromObject:(id)arg1 convertingToJSON:(BOOL)arg2 ;
-(void)dealloc;
@end

