/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:36 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBFragmentModelProtocol.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface FBFragmentModel : NSObject <FBFragmentModelProtocol, NSCopying> {

	FBTree* _fbtree;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(const NodeFactory*)nodeFactory;
+(id)builderForProtocol:(id)arg1 ;
+(id)builderForProtocol:(id)arg1 type:(const char*)arg2 ;
+(Class)classForField:(const StringPiece*)arg1 ;
+(BOOL)resolveInstanceMethod:(SEL)arg1 ;
+(const GeneratedGraphSchema*)schema;
-(id)subscribeWithConsistency:(id)arg1 updateCallback:(/*^block*/id)arg2 failureCallback:(/*^block*/id)arg3 callbackQueue:(id)arg4 ;
-(id)copyBuilder;
-(BOOL)isInstanceOfConcreteGraphQLType:(id)arg1 ;
-(id)graphQLTypeName;
-(id)downcastToProtocol:(id)arg1 ;
-(void)publishToConsistency:(id)arg1 ;
-(id)updateBuilder;
-(id)asFBFragmentModelProtocol:(id)arg1 ;
-(const shared_ptr<facebook::mobile::graphstore::Tree>*)tree;
-(id)initWithTree:(const shared_ptr<facebook::mobile::graphstore::Tree>*)arg1 ;
-(id)initWithFBTree:(FBTree*)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(const shared_ptr<const facebook::mobile::graphstore::NodeSource>*)snapshot;
-(const shared_ptr<facebook::mobile::graphstore::TreeShape>*)fragment;
-(const shared_ptr<const facebook::mobile::graphstore::Record>*)record;
@end

