/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:26 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBGraphQLInput.h>

@class NSString;

@interface FBMessengerInboxItemRecordActionData : FBGraphQLInput {

	NSString* _clientMutationId;
	NSString* _actorId;
	NSString* _itemId;
	NSString* _actionType;
	NSString* _itemLoggingData;
	NSString* _clickTarget;

}

@property (nonatomic,copy) NSString * clientMutationId;              //@synthesize clientMutationId=_clientMutationId - In the implementation block
@property (nonatomic,copy) NSString * actorId;                       //@synthesize actorId=_actorId - In the implementation block
@property (nonatomic,copy) NSString * itemId;                        //@synthesize itemId=_itemId - In the implementation block
@property (nonatomic,copy) NSString * actionType;                    //@synthesize actionType=_actionType - In the implementation block
@property (nonatomic,copy) NSString * itemLoggingData;               //@synthesize itemLoggingData=_itemLoggingData - In the implementation block
@property (nonatomic,copy) NSString * clickTarget;                   //@synthesize clickTarget=_clickTarget - In the implementation block
-(const FBGraphQLInputField*)fieldsMetadataWithOutLength:(out int*)arg1 ;
-(void)setActorId:(NSString *)arg1 ;
-(NSString *)clientMutationId;
-(void)setClientMutationId:(NSString *)arg1 ;
-(NSString *)actorId;
-(NSString *)itemLoggingData;
-(void)setClickTarget:(NSString *)arg1 ;
-(void)setItemLoggingData:(NSString *)arg1 ;
-(NSString *)clickTarget;
-(void)setActionType:(NSString *)arg1 ;
-(NSString *)itemId;
-(void)setItemId:(NSString *)arg1 ;
-(NSString *)actionType;
@end

