/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:24 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBMediaPickerTaggingSearchProvider;
@class NSString, UIButton, UIColor;

@interface FBMediaAttachmentPickerControllerConfiguration : NSObject {

	BOOL _imagePickerEditPhotoEnabled;
	BOOL _allowsIPadSimplePicker;
	BOOL _longPressToBringUpGalleryView;
	BOOL _showPreviewForPhotoAfterCamera;
	long long _preferredPickerStyle;
	unsigned long long _preferredMediaPickerStyle;
	long long _selectionCapability;
	NSString* _sessionID;
	unsigned long long _maxPhotosSelected;
	unsigned long long _maxVideoLength;
	unsigned long long _maxVideoSize;
	id<FBMediaPickerTaggingSearchProvider> _taggingSearchProvider;
	UIButton* _actionButton;
	NSString* _actionTitle;
	UIColor* _previewVCBackgrounColor;

}

@property (nonatomic,readonly) long long preferredPickerStyle;                                            //@synthesize preferredPickerStyle=_preferredPickerStyle - In the implementation block
@property (nonatomic,readonly) unsigned long long preferredMediaPickerStyle;                              //@synthesize preferredMediaPickerStyle=_preferredMediaPickerStyle - In the implementation block
@property (nonatomic,readonly) long long selectionCapability;                                             //@synthesize selectionCapability=_selectionCapability - In the implementation block
@property (nonatomic,copy,readonly) NSString * sessionID;                                                 //@synthesize sessionID=_sessionID - In the implementation block
@property (nonatomic,readonly) unsigned long long maxPhotosSelected;                                      //@synthesize maxPhotosSelected=_maxPhotosSelected - In the implementation block
@property (nonatomic,readonly) unsigned long long maxVideoLength;                                         //@synthesize maxVideoLength=_maxVideoLength - In the implementation block
@property (nonatomic,readonly) unsigned long long maxVideoSize;                                           //@synthesize maxVideoSize=_maxVideoSize - In the implementation block
@property (nonatomic,readonly) BOOL imagePickerEditPhotoEnabled;                                          //@synthesize imagePickerEditPhotoEnabled=_imagePickerEditPhotoEnabled - In the implementation block
@property (nonatomic,readonly) id<FBMediaPickerTaggingSearchProvider> taggingSearchProvider;              //@synthesize taggingSearchProvider=_taggingSearchProvider - In the implementation block
@property (nonatomic,readonly) UIButton * actionButton;                                                   //@synthesize actionButton=_actionButton - In the implementation block
@property (nonatomic,copy,readonly) NSString * actionTitle;                                               //@synthesize actionTitle=_actionTitle - In the implementation block
@property (nonatomic,readonly) BOOL allowsIPadSimplePicker;                                               //@synthesize allowsIPadSimplePicker=_allowsIPadSimplePicker - In the implementation block
@property (nonatomic,readonly) UIColor * previewVCBackgrounColor;                                         //@synthesize previewVCBackgrounColor=_previewVCBackgrounColor - In the implementation block
@property (nonatomic,readonly) BOOL longPressToBringUpGalleryView;                                        //@synthesize longPressToBringUpGalleryView=_longPressToBringUpGalleryView - In the implementation block
@property (nonatomic,readonly) BOOL showPreviewForPhotoAfterCamera;                                       //@synthesize showPreviewForPhotoAfterCamera=_showPreviewForPhotoAfterCamera - In the implementation block
-(id)initWithPreferredPickerStyle:(long long)arg1 preferredMediaPickerStyle:(unsigned long long)arg2 selectionCapability:(long long)arg3 sessionID:(id)arg4 maxPhotosSelected:(unsigned long long)arg5 maxVideoLength:(unsigned long long)arg6 maxVideoSize:(unsigned long long)arg7 imagePickerEditPhotoEnabled:(BOOL)arg8 taggingSearchProvider:(id)arg9 actionButton:(id)arg10 actionTitle:(id)arg11 allowsIPadSimplePicker:(BOOL)arg12 previewVCBackgrounColor:(id)arg13 longPressToBringUpGalleryView:(BOOL)arg14 showPreviewForPhotoAfterCamera:(BOOL)arg15 ;
-(unsigned long long)maxVideoLength;
-(BOOL)longPressToBringUpGalleryView;
-(unsigned long long)maxPhotosSelected;
-(unsigned long long)maxVideoSize;
-(BOOL)showPreviewForPhotoAfterCamera;
-(BOOL)imagePickerEditPhotoEnabled;
-(long long)preferredPickerStyle;
-(unsigned long long)preferredMediaPickerStyle;
-(id<FBMediaPickerTaggingSearchProvider>)taggingSearchProvider;
-(long long)selectionCapability;
-(BOOL)allowsIPadSimplePicker;
-(UIColor *)previewVCBackgrounColor;
-(NSString *)sessionID;
-(UIButton *)actionButton;
-(NSString *)actionTitle;
@end

