/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:23 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBGraphQLQueryBuilder.h>

@interface FBNativeArticleHTMLNativeAdQueryBuilder : FBGraphQLQueryBuilder
+(const FBGraphQLQueryCodegenInitInfo*)initInfoPtr;
+(id)builderWithAdChoicesIconHeight:(id)arg1 adChoicesIconWidth:(id)arg2 adDownloadSessionID:(id)arg3 graphQLID:(id)arg4 iconHeight:(id)arg5 iconWidth:(id)arg6 imageHeight:(id)arg7 imageWidth:(id)arg8 maxObjects:(id)arg9 placementID:(id)arg10 ;
@end

