/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:20 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/CKComponentController.h>
#import <Messenger/FBComponentCollectionViewDataSourceEventListener.h>

@class FBPageComponentFlowComponentContext, NSString;

@interface FBPageComponentFlowDatePickerComponentController : CKComponentController <FBComponentCollectionViewDataSourceEventListener> {

	FBPageComponentFlowComponentContext* _context;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithComponent:(id)arg1 ;
-(void)datePickerComponent:(id)arg1 didSelectDate:(id)arg2 ;
-(void)_updateFormFieldManagerWithDate:(id)arg1 ;
-(void)dataSourceWillBeginUpdates:(id)arg1 ;
-(void)dataSourceDidEndUpdates:(id)arg1 changeset:(Changeset*)arg2 userInfo:(id)arg3 ;
-(void)dealloc;
@end

