/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:37 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UITableViewDataSource.h>

@protocol FBPowerLogsDownloading;
@class FBDiagnosticsAppTimeDownloader, NSDateFormatter, NSArray, NSString;

@interface FBPowerLogsAppViewDataSource : NSObject <UITableViewDataSource> {

	FBDiagnosticsAppTimeDownloader* _downloader;
	NSDateFormatter* _dateFormatter;
	NSArray* _hourIds;
	NSDictionary* _batteryDictionary;
	double _totalEnergy;
	id<FBPowerLogsDownloading> _delegate;

}

@property (assign,nonatomic,__weak) id<FBPowerLogsDownloading> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_didDownloadBatteryIntervals:(NSDictionary*)arg1 ;
-(void)configureWithBatteryDictionary:(id)arg1 ;
-(id)batterySummaryForIndexPath:(id)arg1 ;
-(void)setDelegate:(id<FBPowerLogsDownloading>)arg1 ;
-(id)init;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(id<FBPowerLogsDownloading>)delegate;
-(void)startDownload;
@end

