/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:34 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBQueriedDefaultValueFieldsProtocol
@required
-(long long)minuteValue;
-(long long)hourValue;
-(long long)dayOfWeekValue;
-(id)addressOne;
-(id)zipCode;
-(id)addressTwo;
-(BOOL)booleanValueValue;
-(id)ids;
-(id)thumbnailURLString;
-(id)valueRichtext;
-(id)rawPrice;
-(id)detailURLString;
-(id)state;
-(id)title;
-(id)value;
-(id)subtitle;
-(id)hour;
-(id)minute;
-(id)year;
-(id)month;
-(id)day;
-(id)provider;
-(id)dayOfWeek;
-(id)descriptionText;
-(id)price;
-(id)city;
-(id)email;
-(id)availability;
-(id)itemId;
-(id)firstName;
-(id)lastName;
-(id)phone;
-(id)products;
-(long long)dayValue;
-(long long)monthValue;
-(long long)yearValue;
-(id)productId;
-(id)booleanValue;
-(id)timeEnd;
-(id)timeStart;

@end

