/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSafeCollections : NSObject
+(id)objectOfKind:(Class)arg1 atIndex:(unsigned long long)arg2 fromArray:(id)arg3 ;
+(id)objectOfKind:(Class)arg1 forKey:(id)arg2 fromDictionary:(id)arg3 ;
+(id)dictionaryAtIndex:(unsigned long long)arg1 fromArray:(id)arg2 ;
+(id)arrayAtIndex:(unsigned long long)arg1 fromArray:(id)arg2 ;
+(id)stringAtIndex:(unsigned long long)arg1 fromArray:(id)arg2 ;
+(id)numberAtIndex:(unsigned long long)arg1 fromArray:(id)arg2 ;
+(id)dictionaryForKey:(id)arg1 fromDictionary:(id)arg2 ;
+(id)arrayForKey:(id)arg1 fromDictionary:(id)arg2 ;
+(id)stringForKey:(id)arg1 fromDictionary:(id)arg2 ;
+(id)numberForKey:(id)arg1 fromDictionary:(id)arg2 ;
@end

