/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ACAccountStore, ACAccountType;

@interface FBSystemAccountStoreAdapter : NSObject {

	BOOL _forceBlockingRenew;
	ACAccountStore* _accountStore;
	ACAccountType* _accountTypeFB;

}

@property (nonatomic,retain,readonly) ACAccountStore * accountStore; 
@property (nonatomic,retain,readonly) ACAccountType * accountTypeFB; 
@property (assign) BOOL forceBlockingRenew; 
@property (readonly) BOOL canRequestAccessWithoutUI; 
+(id)sharedInstance;
+(void)setSharedInstance:(id)arg1 ;
-(void)renewSystemAuthorization:(/*^block*/id)arg1 ;
-(void)requestAccessToFacebookAccountStore:(id)arg1 defaultAudience:(unsigned long long)arg2 isReauthorize:(BOOL)arg3 appID:(id)arg4 session:(id)arg5 handler:(/*^block*/id)arg6 ;
-(ACAccountType *)accountTypeFB;
-(BOOL)forceBlockingRenew;
-(void)requestAccessToFacebookAccountStore:(id)arg1 session:(id)arg2 retrying:(BOOL)arg3 handler:(/*^block*/id)arg4 ;
-(id)renewSystemAuthorizationAsTask;
-(BOOL)canRequestAccessWithoutUI;
-(id)requestAccessToFacebookAccountStoreAsTask:(id)arg1 ;
-(void)setForceBlockingRenew:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(ACAccountStore *)accountStore;
@end

