/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:17 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBToastPresentationListener <NSObject>
@required
-(void)toastWillAppear:(id)arg1;
-(void)toastWillDisappear:(id)arg1;
-(void)presenter:(id)arg1 didAcceptToast:(id)arg2;
-(void)presenter:(id)arg1 didRelinquishToast:(id)arg2;

@end

