/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:23 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBTransitioningBlockController <FBContentAwareBlockController>
@optional
+(id)presentationAttributesToPrecompute;
-(void)didBeginTransitionToPresentationAttributes:(id)arg1 withGestureAtPoint:(CGPoint)arg2 originLayout:(id)arg3 destinationLayout:(id)arg4;
-(void)didUpdateTransitionToPresentationAttributes:(id)arg1 withProgress:(double)arg2;
-(void)didUpdateTransitionInteractionWithGestureAtPoint:(CGPoint)arg1;
-(void)willFinishTransitionToPresentationAttributes:(id)arg1 animationConfiguration:(SCD_Struct_FB73)arg2;
-(void)didFinishTransitionToPresentationAttributes:(id)arg1 withResultingLayout:(id)arg2;

@required
-(id)eligiblePresentationAttributesFromTransitioningToPresentationAttributes:(id)arg1;

@end

