/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:38 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBUpdateHandler.h>

@protocol FBURLHandlerDelegate;
@interface FBURLHandler : FBUpdateHandler {

	id<FBURLHandlerDelegate> _installDelegate;

}

@property (assign,nonatomic,__weak) id<FBURLHandlerDelegate> installDelegate;              //@synthesize installDelegate=_installDelegate - In the implementation block
+(void)setDefaultUrl:(id)arg1 ;
-(void)setInstallDelegate:(id<FBURLHandlerDelegate>)arg1 ;
-(id)initWithUrl:(id)arg1 ;
-(id<FBURLHandlerDelegate>)installDelegate;
-(void)processUpdate:(id)arg1 ;
-(void)cancel;
-(id)init;
@end

