/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:24 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface MNContactSearchStandardSourcesConfigurationBuilder : NSObject {

	BOOL _includeUsers;
	BOOL _includeGroups;
	BOOL _includePages;
	BOOL _includeVCEndpoints;
	BOOL _includeGames;
	BOOL _includeInternalBots;
	BOOL _includeSecureThreads;
	BOOL _includeAddressBookEntries;
	BOOL _includeNetworkResults;

}
+(id)contactSearchStandardSourcesConfiguration;
+(id)contactSearchStandardSourcesConfigurationFromExistingContactSearchStandardSourcesConfiguration:(id)arg1 ;
-(id)withIncludeSecureThreads:(BOOL)arg1 ;
-(id)withIncludeVCEndpoints:(BOOL)arg1 ;
-(id)withIncludeInternalBots:(BOOL)arg1 ;
-(id)withIncludeGames:(BOOL)arg1 ;
-(id)withIncludeUsers:(BOOL)arg1 ;
-(id)withIncludeGroups:(BOOL)arg1 ;
-(id)withIncludePages:(BOOL)arg1 ;
-(id)withIncludeAddressBookEntries:(BOOL)arg1 ;
-(id)withIncludeNetworkResults:(BOOL)arg1 ;
-(id)build;
@end

