/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:21 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNAbstractComposerTrayExtension.h>
#import <Messenger/MNContactSharePickerViewControllerDelegate.h>
#import <Messenger/FBClassProvidable.h>

@protocol MNModalPresentation, FBProvider;
@class MNComposerExtensionTrayPresentationStrategy, NSString;

@interface MNComposerContactShareExtension : MNAbstractComposerTrayExtension <MNContactSharePickerViewControllerDelegate, FBClassProvidable> {

	MNComposerExtensionTrayPresentationStrategy* _presentationStrategy;
	id<MNModalPresentation> _modalPresenter;
	id<FBProvider> _contactSharePickerViewControllerProvider;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithProviderMapData:(id)arg1 ;
-(id)_composerIcon;
-(id)extensionModule;
-(void)didSelect:(BOOL)arg1 ;
-(BOOL)shouldPresent:(BOOL)arg1 ;
-(id)presentationStrategy;
-(id)viewControllerForPresentation;
-(id)initWithModalPresenter:(id)arg1 contactSharePickerViewControllerProvider:(id)arg2 ;
-(void)_presentContactShareView;
-(id)_contactSharePickerViewController;
-(void)contactSharePickerViewControllerDidDismiss:(id)arg1 ;
-(void)contactSharePickerViewControllerDidSelectContact:(id)arg1 ;
-(id)extensionIdentifier;
-(long long)category;
-(id)tabBarItem;
@end

