/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:23 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBCancelable.h>

@protocol FBServiceTransactionMutating, OS_dispatch_queue, MNGroupsRoomsFetchResultsHandling;
@class FBGraphQLQuery, FBMemPageInfo, FBUserSession, NSObject;

@interface MNGroupsRoomsFetcher : NSObject <FBCancelable> {

	FBGraphQLQuery* _graphQLQuery;
	id<FBServiceTransactionMutating> _graphQLFetchRequest;
	FBMemPageInfo* _pageInfo;
	FBUserSession* _session;
	NSObject*<OS_dispatch_queue> _queue;
	id<MNGroupsRoomsFetchResultsHandling> _resultsHandler;

}
-(void)_runRoomsGraphQLRoomsQueryWithPageInfo:(id)arg1 requestPriority:(long long)arg2 callPath:(id)arg3 success:(/*^block*/id)arg4 failure:(/*^block*/id)arg5 ;
-(void)_handleGraphQLFetchSuccessWithResponse:(id)arg1 success:(/*^block*/id)arg2 failure:(/*^block*/id)arg3 ;
-(id)initWithSession:(id)arg1 resultsHandler:(id)arg2 queue:(id)arg3 ;
-(void)beginFetchingRoomsWithSuccess:(/*^block*/id)arg1 failure:(/*^block*/id)arg2 ;
-(BOOL)hasMoreRoomsToFetch;
-(void)fetchMoreRoomsWithSuccess:(/*^block*/id)arg1 failure:(/*^block*/id)arg2 ;
-(void)cancel;
@end

