/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:20 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBInjecting.h>

@protocol FBIntentHandler;
@class FBProviderMapData, FBMobileConfigContextManager, MNRoomShareSheetThreadConfigurationFactory, MNJoinableGroupShareController, FBUserSession, MNThreadImageManager, MNProfileImageViewController, MNDateFormatter, MNThreadParticipantNameFormatter, NSString;

@interface MNGroupsRoomShareBannerControllerInjector : NSObject <FBInjecting> {

	FBProviderMapData* _mapData;
	FBMobileConfigContextManager* _mobileConfigContextManager;
	MNRoomShareSheetThreadConfigurationFactory* _shareSheetThreadConfigurationFactory;
	MNJoinableGroupShareController* _joinableGroupShareController;
	FBUserSession* _session;
	MNThreadImageManager* _threadImageManager;
	MNProfileImageViewController* _profileImageViewController;
	MNDateFormatter* _dateFormatter;
	MNThreadParticipantNameFormatter* _nameFormatter;
	id<FBIntentHandler> _intentHandler;

}

@property (nonatomic,readonly) FBMobileConfigContextManager * mobileConfigContextManager;                                      //@synthesize mobileConfigContextManager=_mobileConfigContextManager - In the implementation block
@property (nonatomic,readonly) MNRoomShareSheetThreadConfigurationFactory * shareSheetThreadConfigurationFactory;              //@synthesize shareSheetThreadConfigurationFactory=_shareSheetThreadConfigurationFactory - In the implementation block
@property (nonatomic,readonly) MNJoinableGroupShareController * joinableGroupShareController;                                  //@synthesize joinableGroupShareController=_joinableGroupShareController - In the implementation block
@property (nonatomic,readonly) FBUserSession * session;                                                                        //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) MNThreadImageManager * threadImageManager;                                                      //@synthesize threadImageManager=_threadImageManager - In the implementation block
@property (nonatomic,readonly) MNProfileImageViewController * profileImageViewController;                                      //@synthesize profileImageViewController=_profileImageViewController - In the implementation block
@property (nonatomic,readonly) MNDateFormatter * dateFormatter;                                                                //@synthesize dateFormatter=_dateFormatter - In the implementation block
@property (nonatomic,readonly) MNThreadParticipantNameFormatter * nameFormatter;                                               //@synthesize nameFormatter=_nameFormatter - In the implementation block
@property (nonatomic,readonly) id<FBIntentHandler> intentHandler;                                                              //@synthesize intentHandler=_intentHandler - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)instanceWithInjector:(id)arg1 ;
-(id)initWithProviderMapData:(id)arg1 ;
-(FBMobileConfigContextManager *)mobileConfigContextManager;
-(MNProfileImageViewController *)profileImageViewController;
-(MNThreadImageManager *)threadImageManager;
-(MNJoinableGroupShareController *)joinableGroupShareController;
-(MNRoomShareSheetThreadConfigurationFactory *)shareSheetThreadConfigurationFactory;
-(id<FBIntentHandler>)intentHandler;
-(MNThreadParticipantNameFormatter *)nameFormatter;
-(FBUserSession *)session;
-(MNDateFormatter *)dateFormatter;
@end

