/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol NSCopying;
@class NSArray, NSObject;

@interface MNListModelItemKeys : FBValueObject <NSCopying> {

	NSArray* _itemKeys;
	NSObject*<NSCopying> _listMetadata;

}

@property (nonatomic,copy,readonly) NSArray * itemKeys;                             //@synthesize itemKeys=_itemKeys - In the implementation block
@property (nonatomic,copy,readonly) NSObject*<NSCopying> listMetadata;              //@synthesize listMetadata=_listMetadata - In the implementation block
-(NSArray *)itemKeys;
-(NSObject*<NSCopying>)listMetadata;
-(id)initWithItemKeys:(id)arg1 listMetadata:(id)arg2 ;
@end

