/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:19 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <Messenger/MNMessageReactionsMenuButtonDelegate.h>

@protocol MNMessageReactionsContextMenuViewDelegate;
@class NSArray, UIView, UILabel, MNMessageReactionsContextMenuViewModel, NSString;

@interface MNMessageReactionsContextMenuView : UIView <MNMessageReactionsMenuButtonDelegate> {

	NSArray* _buttons;
	UIView* _separator;
	UILabel* _upsellLabel;
	MNMessageReactionsContextMenuViewModel* _contextMenuViewModel;
	id<MNMessageReactionsContextMenuViewDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNMessageReactionsContextMenuViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithContextMenuViewModel:(id)arg1 ;
-(void)_initializeWithContextMenuActions:(id)arg1 ;
-(void)_initializeWithUpsellString:(id)arg1 ;
-(void)_layoutContextMenuActionButtons;
-(void)_layoutUpsellLabel;
-(void)messageReactionsMenuButtonWasTapped:(id)arg1 ;
-(void)setDelegate:(id<MNMessageReactionsContextMenuViewDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<MNMessageReactionsContextMenuViewDelegate>)delegate;
@end

