/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:24 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class MNThreadMontageThumbnail, MNProfileImageModel, FBMUser, FBMMontageAudience, NSString;

@interface MNMontageSingleStatusHeadViewModel : FBValueObject <NSCopying> {

	MNThreadMontageThumbnail* _thumbnail;
	MNProfileImageModel* _profileImageModel;
	FBMUser* _author;
	FBMMontageAudience* _audience;
	NSString* _timestampText;

}

@property (nonatomic,copy,readonly) MNThreadMontageThumbnail * thumbnail;                 //@synthesize thumbnail=_thumbnail - In the implementation block
@property (nonatomic,copy,readonly) MNProfileImageModel * profileImageModel;              //@synthesize profileImageModel=_profileImageModel - In the implementation block
@property (nonatomic,copy,readonly) FBMUser * author;                                     //@synthesize author=_author - In the implementation block
@property (nonatomic,copy,readonly) FBMMontageAudience * audience;                        //@synthesize audience=_audience - In the implementation block
@property (nonatomic,copy,readonly) NSString * timestampText;                             //@synthesize timestampText=_timestampText - In the implementation block
-(MNProfileImageModel *)profileImageModel;
-(NSString *)timestampText;
-(id)initWithThumbnail:(id)arg1 profileImageModel:(id)arg2 author:(id)arg3 audience:(id)arg4 timestampText:(id)arg5 ;
-(MNThreadMontageThumbnail *)thumbnail;
-(FBMUser *)author;
-(FBMMontageAudience *)audience;
@end

