/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:17 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNUrlHandlerExtending.h>

@protocol FBProvider;
@class MNProfilePictureSelectionViewControllerPresenter, NSString;

@interface MNProfilePictureSelectionUrlHandler : NSObject <MNUrlHandlerExtending> {

	id<FBProvider> _profilePictureSelectionViewControllerPresenterProvider;
	MNProfilePictureSelectionViewControllerPresenter* _profilePictureSelectionViewControllerPresenter;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)analyticsModule;
-(BOOL)canOpenURL:(id)arg1 sourceApplication:(id)arg2 ;
-(BOOL)openURL:(id)arg1 sourceApplication:(id)arg2 ;
-(BOOL)isPublic;
-(id)initWithProfilePictureSelectionViewControllerPresenterProvider:(id)arg1 ;
@end

