/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:24 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNServiceControllable.h>

@protocol MNMessageSendQuerying, MNMessageSendAnalyticsLogging, MNAuthenticationManager, MNRecentMessagesTracking;
@class MNPushMessageReceivedListeningAnnouncer, MNMessageSendSchedulerListeningAnnouncer, MNRecentMessagesTracker, MNMessageSendBugReporter, NSString;

@interface MNRecentMessagesTrackingService : NSObject <MNServiceControllable> {

	id<MNMessageSendQuerying> _messageSendQuerier;
	id<MNMessageSendAnalyticsLogging> _messageSendAnalyticsLogger;
	id<MNAuthenticationManager> _authManager;
	MNPushMessageReceivedListeningAnnouncer* _pushAnnouncer;
	MNMessageSendSchedulerListeningAnnouncer* _sendAnnouncer;
	MNRecentMessagesTracker* _tracker;
	id<MNRecentMessagesTracking> _queueDispatchedTracker;
	MNMessageSendBugReporter* _sendBugReporter;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithSendQuerier:(id)arg1 sendAnaltyicsLogger:(id)arg2 authManager:(id)arg3 pushAnnouncer:(id)arg4 sendAnnouncer:(id)arg5 ;
-(void)stop;
-(void)start:(id)arg1 ;
-(void)handleIdle;
@end

