/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:24 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNDefaultAttachmentCellElementController.h>
#import <Messenger/MNRoomShareAttachmentViewDelegate.h>

@protocol FBIntentHandler, MNAvatarImageDecorating;
@class MNProfileImageViewController, FBUserSession, NSString;

@interface MNRoomShareAttachmentCellElementController : MNDefaultAttachmentCellElementController <MNRoomShareAttachmentViewDelegate> {

	id<FBIntentHandler> _intentHandler;
	id<MNAvatarImageDecorating> _avatarImageDecoration;
	MNProfileImageViewController* _profileImageViewController;
	FBUserSession* _session;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)awakeWithView:(id)arg1 delegate:(id)arg2 actionHandler:(id)arg3 ;
-(void)willAppearWithViewModel:(id)arg1 threadKey:(id)arg2 inContainerView:(id)arg3 ;
-(void)didDisappearInContainerView:(id)arg1 ;
-(void)shareAttachmentViewDidSelectViewRoom:(id)arg1 withJoinableLink:(id)arg2 ;
-(id)initWithIntentHandler:(id)arg1 profileImageViewController:(id)arg2 avatarImageDecoration:(id)arg3 session:(id)arg4 ;
@end

