/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:18 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNThreadClientSummaryUpdateCreating, MNThreadDetailsSecureCodenameEditControllerDelegate;
@class MNThreadUpdateRunningService, FBAlertViewCoordinator, FBMSecureThreadProperties;

@interface MNThreadDetailsSecureCodenameEditController : NSObject {

	MNThreadUpdateRunningService* _updateService;
	FBAlertViewCoordinator* _alertViewController;
	FBMSecureThreadProperties* _secureThreadProperties;
	id<MNThreadClientSummaryUpdateCreating> _summaryUpdateCreator;
	id<MNThreadDetailsSecureCodenameEditControllerDelegate> _delegate;

}
-(void)_configureAlertView:(id)arg1 ;
-(void)_handleTapOnButtonWithIndex:(long long)arg1 onAlertView:(id)arg2 wasTriggeredByUser:(BOOL)arg3 ;
-(id)initWithThreadUpdateService:(id)arg1 alertController:(id)arg2 secureThreadProperties:(id)arg3 summaryUpdateCreator:(id)arg4 delegate:(id)arg5 ;
-(void)displayAlert;
@end

