/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:24 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, MNPlainPhotoSource, NSURL;

@interface MNVideoAttachmentViewModel : FBValueObject <NSCopying> {

	BOOL _showSoundButton;
	NSString* _offlineVideoId;
	NSString* _videoFbId;
	MNPlainPhotoSource* _thumbnailPhotoSource;
	long long _videoType;
	NSURL* _videoURL;
	double _videoWidth;
	double _videoHeight;
	double _duration;
	long long _fileSizeInBytes;

}

@property (nonatomic,copy,readonly) NSString * offlineVideoId;                              //@synthesize offlineVideoId=_offlineVideoId - In the implementation block
@property (nonatomic,copy,readonly) NSString * videoFbId;                                   //@synthesize videoFbId=_videoFbId - In the implementation block
@property (nonatomic,copy,readonly) MNPlainPhotoSource * thumbnailPhotoSource;              //@synthesize thumbnailPhotoSource=_thumbnailPhotoSource - In the implementation block
@property (nonatomic,readonly) long long videoType;                                         //@synthesize videoType=_videoType - In the implementation block
@property (nonatomic,copy,readonly) NSURL * videoURL;                                       //@synthesize videoURL=_videoURL - In the implementation block
@property (nonatomic,readonly) double videoWidth;                                           //@synthesize videoWidth=_videoWidth - In the implementation block
@property (nonatomic,readonly) double videoHeight;                                          //@synthesize videoHeight=_videoHeight - In the implementation block
@property (nonatomic,readonly) double duration;                                             //@synthesize duration=_duration - In the implementation block
@property (nonatomic,readonly) long long fileSizeInBytes;                                   //@synthesize fileSizeInBytes=_fileSizeInBytes - In the implementation block
@property (nonatomic,readonly) BOOL showSoundButton;                                        //@synthesize showSoundButton=_showSoundButton - In the implementation block
-(MNPlainPhotoSource *)thumbnailPhotoSource;
-(NSString *)offlineVideoId;
-(double)videoWidth;
-(double)videoHeight;
-(long long)fileSizeInBytes;
-(NSString *)videoFbId;
-(BOOL)showSoundButton;
-(id)initWithOfflineVideoId:(id)arg1 videoFbId:(id)arg2 thumbnailPhotoSource:(id)arg3 videoType:(long long)arg4 videoURL:(id)arg5 videoWidth:(double)arg6 videoHeight:(double)arg7 duration:(double)arg8 fileSizeInBytes:(long long)arg9 showSoundButton:(BOOL)arg10 ;
-(double)duration;
-(long long)videoType;
-(NSURL *)videoURL;
@end

