/*
* This header is generated by classdump-dyld 1.0
* on Sunday, January 22, 2017 at 11:26:40 AM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/DB24BCEF-8CEA-41B1-9C55-8893795309EE/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ZZArchiveEntryWriter
@required
-(unsigned)offsetToLocalFileEnd;
-(BOOL)writeLocalFileToChannelOutput:(id)arg1 withInitialSkip:(unsigned)arg2 error:(out id*)arg3;
-(BOOL)writeCentralFileHeaderToChannelOutput:(id)arg1 error:(out id*)arg2;

@end

