/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:57 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSNumber;

@interface _RCTTimer : NSObject {

	BOOL _repeats;
	NSDate* _target;
	NSNumber* _callbackID;
	double _interval;

}

@property (nonatomic,readonly) NSDate * target;                         //@synthesize target=_target - In the implementation block
@property (nonatomic,readonly) BOOL repeats;                            //@synthesize repeats=_repeats - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * callbackID;              //@synthesize callbackID=_callbackID - In the implementation block
@property (nonatomic,readonly) double interval;                         //@synthesize interval=_interval - In the implementation block
-(id)initWithCallbackID:(id)arg1 interval:(double)arg2 targetTime:(double)arg3 repeats:(BOOL)arg4 ;
-(BOOL)shouldFire:(id)arg1 ;
-(NSNumber *)callbackID;
-(NSDate *)target;
-(BOOL)repeats;
-(double)interval;
-(void)reschedule;
@end

