/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@protocol FBBrowserRelatedStoryTileViewDelegate;
@class UIImageView, UILabel, NSString, FBUserSession;

@interface FBBrowserRelatedStoryTileView : UIView {

	UIImageView* _imageView;
	UILabel* _titleLabel;
	UILabel* _sourceLabel;
	NSString* _imageURL;
	NSString* _storyURL;
	FBUserSession* _session;
	id<FBBrowserRelatedStoryTileViewDelegate> _relatedStoryTileViewDelegate;

}
-(void)storyTapped:(id)arg1 ;
-(void)downloadImage;
-(id)initWithTitle:(id)arg1 source:(id)arg2 storyURL:(id)arg3 imageURL:(id)arg4 relatedStoryTileViewDelegate:(id)arg5 session:(id)arg6 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

