/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:59 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBNetworkerRequest.h>

@class NSString;

@interface FBDBLSetNonceRequest : FBNetworkerRequest {

	NSString* _accountID;
	NSString* _nonceValue;
	NSString* _providedPin;
	NSString* _machineID;
	NSString* _accessToken;

}

@property (nonatomic,copy) NSString * accountID;                //@synthesize accountID=_accountID - In the implementation block
@property (nonatomic,copy) NSString * nonceValue;               //@synthesize nonceValue=_nonceValue - In the implementation block
@property (nonatomic,copy) NSString * providedPin;              //@synthesize providedPin=_providedPin - In the implementation block
@property (nonatomic,copy) NSString * machineID;                //@synthesize machineID=_machineID - In the implementation block
@property (nonatomic,copy) NSString * accessToken;              //@synthesize accessToken=_accessToken - In the implementation block
-(void)setNonceValue:(NSString *)arg1 ;
-(NSString *)nonceValue;
-(void)setProvidedPin:(NSString *)arg1 ;
-(id)initWithAccountID:(id)arg1 nonceValue:(id)arg2 providedPin:(id)arg3 machineID:(id)arg4 accessToken:(id)arg5 callbackPerformer:(id)arg6 ;
-(NSString *)providedPin;
-(id)networkRequest;
-(BOOL)allowRetry;
-(void)setMachineID:(NSString *)arg1 ;
-(void)setAccessToken:(NSString *)arg1 ;
-(void)setAccountID:(NSString *)arg1 ;
-(NSString *)accountID;
-(NSString *)machineID;
-(NSString *)accessToken;
@end

