/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:50 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/ASDisplayNode.h>
#import <Messenger/FBExpandabilityHookProtocol.h>

@interface FBExpandableNode : ASDisplayNode <FBExpandabilityHookProtocol> {

	double _expansionProgress;
	unsigned long long _expansionState;
	unsigned long long _previousExpansionState;

}

@property (nonatomic,readonly) double expansionProgress;                               //@synthesize expansionProgress=_expansionProgress - In the implementation block
@property (assign,nonatomic) unsigned long long expansionState;                        //@synthesize expansionState=_expansionState - In the implementation block
@property (nonatomic,readonly) unsigned long long previousExpansionState;              //@synthesize previousExpansionState=_previousExpansionState - In the implementation block
-(void)_staticInitialize;
-(unsigned long long)expansionState;
-(void)willCollapseWithAnimationConfiguration:(SCD_Struct_FB29)arg1 ;
-(void)willExpandWithAnimationConfiguration:(SCD_Struct_FB29)arg1 ;
-(void)didBeginExpansionInteractionAtPoint:(CGPoint)arg1 ;
-(void)didUpdateExpansionInteractionAtPoint:(CGPoint)arg1 ;
-(void)didCollapse;
-(void)didExpand;
-(void)setExpansionState:(unsigned long long)arg1 ;
-(void)didUpdateForExpansionProgress:(double)arg1 ;
-(double)expansionProgress;
-(unsigned long long)previousExpansionState;
@end

