/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:28:01 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBToastQueuing.h>

@protocol FBToastQueuing;
@class NSString;

@interface FBFilteredToastQueue : NSObject <FBToastQueuing> {

	/*^block*/id _predicate;
	id<FBToastQueuing> _queue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithToastQueue:(id)arg1 predicate:(/*^block*/id)arg2 ;
-(void)queueToast:(id)arg1 ;
-(void)removeToast:(id)arg1 ;
-(id)peek;
-(BOOL)isEmpty;
-(id)dequeue;
@end

