/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:56 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBAppService.h>

@class FBMQTTManager, FBUserSession, NSMutableArray, NSString;

@interface FBFriendingPossibilitiesMQTTBroadcaster : NSObject <FBAppService> {

	FBMQTTManager* _mqttManager;
	FBUserSession* _session;
	NSMutableArray* _mqttListeners;
	BOOL _subscribedToMQTT;

}

@property (nonatomic,readonly) BOOL subscribedToMQTT;               //@synthesize subscribedToMQTT=_subscribedToMQTT - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_processNewRequestWithFriendFBID:(id)arg1 ;
-(void)_processRemovedRequestWithFriendFBID:(id)arg1 ;
-(void)_processFriendRequestsSeen;
-(void)_subscribeToMQTT;
-(void)_unsubscribeFromMQTT;
-(BOOL)subscribedToMQTT;
-(void)startAppService;
-(void)stopAppService;
-(id)initWithSession:(id)arg1 ;
@end

