/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:28:02 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBFramePerformanceResultDisplayer.h>

@protocol FBFramePerformanceTrackerLogger;
@class NSString;

@interface FBFramePerformanceTracker : NSObject <FBFramePerformanceResultDisplayer> {

	id<FBFramePerformanceTrackerLogger> _logger;
	FBFramePerformanceTrackerConfig _config;
	mutex _lock;
	BOOL _tracking;
	long long _updateCount;
	unsigned long long _startTime;
	unsigned long long _previousFrameTimestamp;
	unsigned long long _lastFrameInterval;
	unsigned long long _targetFrameTime;
	FrameDrops _frameDrops;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)framePerformanceTrackingLogging;
-(void)startTrackingWithTargetFPS:(long long)arg1 ;
-(void)updateFrameWithTimestamp:(unsigned long long)arg1 ;
-(FBFramePerformanceResult)currentPerformanceResult;
-(FBFramePerformanceResult)_trackingResult;
-(id)init;
-(void)_reset;
-(void)stopTracking;
-(id)initWithConfig:(FBFramePerformanceTrackerConfig)arg1 ;
-(void)setLogger:(id)arg1 ;
@end

