/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:57 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURL, FBUserSession;

@interface FBGIFResultViewSpecifier : NSObject {

	NSURL* _animatedGIFURL;
	FBUserSession* _session;

}

@property (nonatomic,copy,readonly) NSURL * animatedGIFURL;              //@synthesize animatedGIFURL=_animatedGIFURL - In the implementation block
@property (nonatomic,readonly) FBUserSession * session;                  //@synthesize session=_session - In the implementation block
-(id)initWithAnimagedImageURL:(id)arg1 session:(id)arg2 ;
-(NSURL *)animatedGIFURL;
-(FBUserSession *)session;
@end

