/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <FBSharedFramework/CKStatefulViewComponent.h>

@class FBUserSession;

@interface FBListViewCollectionComponent : CKStatefulViewComponent {

	/*function pointer*/void* _sectionComponentProviderFunction;
	/*function pointer*/void* _componentContextFunction;
	FBUserSession* _session;
	FBComponentViewControllerWildeContext _viewControllerContext;
	FBListViewCollectionComponentOptions* _options;

}

@property (assign,nonatomic) /*function pointer*/void* sectionComponentProviderFunction;               //@synthesize sectionComponentProviderFunction=_sectionComponentProviderFunction - In the implementation block
@property (assign,nonatomic) /*function pointer*/void* componentContextFunction;                       //@synthesize componentContextFunction=_componentContextFunction - In the implementation block
@property (assign,nonatomic) FBComponentViewControllerWildeContext viewControllerContext;              //@synthesize viewControllerContext=_viewControllerContext - In the implementation block
@property (assign,nonatomic) FBListViewCollectionComponentOptions* options;                            //@synthesize options=_options - In the implementation block
@property (nonatomic,retain) FBUserSession * session;                                                  //@synthesize session=_session - In the implementation block
+(id)newWithChildrenSectionComponent:(/*function pointer*/void*)arg1 sectionComponentContextFunction:(/*function pointer*/void*)arg2 viewControllerContext:(FBComponentViewControllerWildeContext)arg3 options:(FBListViewCollectionComponentOptions*)arg4 session:(id)arg5 size:(const CKComponentSize*)arg6 ;
+(id)newWithChildrenSectionComponent:(/*function pointer*/void*)arg1 context:(/*function pointer*/void*)arg2 analyticsModule:(id)arg3 options:(FBListViewCollectionComponentOptions*)arg4 session:(id)arg5 size:(const CKComponentSize*)arg6 ;
-(/*function pointer*/void*)sectionComponentProviderFunction;
-(void)setSectionComponentProviderFunction:(/*function pointer*/void*)arg1 ;
-(/*function pointer*/void*)componentContextFunction;
-(void)setComponentContextFunction:(/*function pointer*/void*)arg1 ;
-(FBComponentViewControllerWildeContext)viewControllerContext;
-(void)setViewControllerContext:(FBComponentViewControllerWildeContext)arg1 ;
-(FBListViewCollectionComponentOptions*)options;
-(void)setOptions:(FBListViewCollectionComponentOptions*)arg1 ;
-(void)setSession:(FBUserSession *)arg1 ;
-(FBUserSession *)session;
@end

