/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:57 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBMemorializedFriendsProviderDelegate;
@class NSMutableSet, FBMemPagedDownloadController, FBUserSession;

@interface FBMemorializedFriendsProvider : NSObject {

	NSMutableSet* _memorializedFriends;
	FBMemPagedDownloadController* _downloadController;
	FBUserSession* _session;
	id<FBMemorializedFriendsProviderDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBMemorializedFriendsProviderDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_loadNextPage;
-(void)_processIncrementalResults:(id)arg1 error:(id)arg2 ;
-(void)fetchMemorializedFriends;
-(void)setDelegate:(id<FBMemorializedFriendsProviderDelegate>)arg1 ;
-(id<FBMemorializedFriendsProviderDelegate>)delegate;
-(id)initWithSession:(id)arg1 ;
@end

