/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:57 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBFeedEdgeSource;

@interface FBMemStoryStreamResponseHandlerStreamContext : NSObject {

	BOOL _isLastResponse;
	unsigned long long _loadType;
	FBFeedEdgeSource* _source;

}

@property (nonatomic,readonly) unsigned long long loadType;              //@synthesize loadType=_loadType - In the implementation block
@property (nonatomic,readonly) BOOL isLastResponse;                      //@synthesize isLastResponse=_isLastResponse - In the implementation block
@property (nonatomic,readonly) FBFeedEdgeSource * source;                //@synthesize source=_source - In the implementation block
-(id)initWithLoadType:(unsigned long long)arg1 isLastResponse:(BOOL)arg2 source:(id)arg3 ;
-(BOOL)isLastResponse;
-(FBFeedEdgeSource *)source;
-(unsigned long long)loadType;
@end

