/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIButton.h>

@class NSString, UIImage;

@interface FBPaymentsButton : UIButton {

	NSString* _title;
	UIImage* _image;
	long long _buttonState;

}

@property (assign,nonatomic) long long buttonState;              //@synthesize buttonState=_buttonState - In the implementation block
+(CGSize)sizeWithTitle:(id)arg1 ;
-(void)setButtonState:(long long)arg1 ;
-(void)_configButton;
-(long long)buttonState;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id)initWithImage:(id)arg1 ;
-(id)initWithTitle:(id)arg1 ;
@end

