/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:28:01 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface FBPremiumVideoAdSRTCaption : NSObject {

	double _from;
	double _to;
	NSString* _caption;

}

@property (nonatomic,readonly) double from;                          //@synthesize from=_from - In the implementation block
@property (nonatomic,readonly) double to;                            //@synthesize to=_to - In the implementation block
@property (nonatomic,copy,readonly) NSString * caption;              //@synthesize caption=_caption - In the implementation block
-(id)initWithCaption:(id)arg1 from:(double)arg2 to:(double)arg3 ;
-(NSString *)caption;
-(double)from;
-(double)to;
@end

