/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBRtcExpressionCellModel.h>

@class MNMediaFilterDescriptor;

@interface FBRtcExpressionMaskCellModel : FBRtcExpressionCellModel {

	MNMediaFilterDescriptor* _filter;

}

@property (nonatomic,readonly) MNMediaFilterDescriptor * filter;              //@synthesize filter=_filter - In the implementation block
-(id)initWithFilter:(id)arg1 session:(id)arg2 ;
-(MNMediaFilterDescriptor *)filter;
@end

