/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:58 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/FBStructuredSurveyUICell.h>

@protocol FBStructuredSurveyUIIconScaleCellDelegate;
@class NSMutableArray, FBUserSession;

@interface FBStructuredSurveyUIIconScaleCell : FBStructuredSurveyUICell {

	NSMutableArray* _iconViews;
	NSMutableArray* _iconButtons;
	id<FBStructuredSurveyUIIconScaleCellDelegate> _delegate;
	FBUserSession* _session;

}

@property (assign,nonatomic,__weak) id<FBStructuredSurveyUIIconScaleCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) FBUserSession * session;                                             //@synthesize session=_session - In the implementation block
+(double)heightForModelObject:(id)arg1 context:(id)arg2 frame:(CGRect)arg3 styleSheet:(id)arg4 config:(id)arg5 ;
-(void)configureWithModelObject:(id)arg1 context:(id)arg2 ;
-(void)touched:(id)arg1 ;
-(void)cancelled:(id)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<FBStructuredSurveyUIIconScaleCellDelegate>)arg1 ;
-(id<FBStructuredSurveyUIIconScaleCellDelegate>)delegate;
-(void)setSession:(FBUserSession *)arg1 ;
-(FBUserSession *)session;
-(void)tapped:(id)arg1 ;
@end

