/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:28:01 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIViewController.h>

@class UIViewController, BFTaskCompletionSource, UIView;

@interface FBTarotTransferableViewController : UIViewController {

	unique_ptr<FB::Input<bool>, std::__1::default_delete<FB::Input<bool> > >* _hasContentViewControllerInput;
	UIViewController* _contentViewController;
	FBTarotTransferableViewController* _existingTransferableViewController;
	BFTaskCompletionSource* _viewLoadedTaskCompletionSource;
	UIView* _snapshotView;
	Signal<bool>* _hasContentViewController;

}

@property (nonatomic,retain) UIViewController * contentViewController;                                              //@synthesize contentViewController=_contentViewController - In the implementation block
@property (nonatomic,readonly) FBTarotTransferableViewController * existingTransferableViewController;              //@synthesize existingTransferableViewController=_existingTransferableViewController - In the implementation block
@property (nonatomic,readonly) BFTaskCompletionSource * viewLoadedTaskCompletionSource;                             //@synthesize viewLoadedTaskCompletionSource=_viewLoadedTaskCompletionSource - In the implementation block
@property (nonatomic,retain) UIView * snapshotView;                                                                 //@synthesize snapshotView=_snapshotView - In the implementation block
@property (nonatomic,readonly) Signal<bool>* hasContentViewController;                                              //@synthesize hasContentViewController=_hasContentViewController - In the implementation block
-(id)newTransferableViewController;
-(id)initWithExistingTransferableViewController:(id)arg1 ;
-(FBTarotTransferableViewController *)existingTransferableViewController;
-(BFTaskCompletionSource *)viewLoadedTaskCompletionSource;
-(void)dealloc;
-(UIView *)snapshotView;
-(void)viewDidLayoutSubviews;
-(UIViewController *)contentViewController;
-(void)viewDidLoad;
-(id)childViewControllerForStatusBarStyle;
-(id)childViewControllerForStatusBarHidden;
-(id)initWithContentViewController:(id)arg1 ;
-(void)setContentViewController:(UIViewController *)arg1 ;
-(void)setSnapshotView:(UIView *)arg1 ;
-(Signal<bool>*)hasContentViewController;
@end

