/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:52 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@protocol FBQueriedVideoChannelFieldsProtocol;
@class FBMorphableButton, FBMorphableButtonContent, FBMemModelObject, NSString, FBUserSession, NSOperationQueue;

@interface FBVideoHomeFollowButton : UIView {

	FBMorphableButton* _button;
	FBMorphableButtonContent* _followButtonContent;
	FBMorphableButtonContent* _followingButtonContent;
	FBMemModelObject*<FBQueriedVideoChannelFieldsProtocol> _videoChannel;
	NSString* _videoID;
	FBUserSession* _session;
	BOOL _darkBackground;
	unsigned long long _sizeStyle;
	long long _buttonAlignment;
	BOOL _showVideoHomeTabItemBling;
	BOOL _hideIfAlreadyFollowing;
	BOOL _stateWasAlreadyFollowingOrSubscribed;
	/*^block*/id _videoHomeSessionIDProvider;
	/*^block*/id _stateToggledToBlock;
	NSOperationQueue* _queueForNextFollowedCLCUpdate;
	BOOL _disableNotificationView;

}
-(void)_followingValueDidChange:(id)arg1 ;
-(id)initWithVideoChannel:(id)arg1 videoID:(id)arg2 session:(id)arg3 darkBackground:(BOOL)arg4 sizeStyle:(unsigned long long)arg5 buttonAlignment:(long long)arg6 showVideoHomeTabItemBling:(BOOL)arg7 hideIfAlreadyFollowing:(BOOL)arg8 disableNotificationView:(BOOL)arg9 videoHomeSessionIDProvider:(/*^block*/id)arg10 stateToggledToBlock:(/*^block*/id)arg11 ;
-(void)_layoutSubviewsInternal:(BOOL)arg1 ;
-(void)_didTapFollowButton;
-(void)_didTapFollowingButton;
-(void)_animateVideoTabItemBling;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
@end

