/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:28:01 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBVideoFilmstripVideoSourceProtocol;
@class UIImage;

@interface FBVideoFilmstripFrameViewModel : NSObject {

	/*^block*/id _requestCancelBlock;
	id<FBVideoFilmstripVideoSourceProtocol> _videoSource;
	unsigned long long _frameIndex;
	BOOL _placeholder;
	UIImage* _image;

}

@property (nonatomic,retain) UIImage * image;                                      //@synthesize image=_image - In the implementation block
@property (getter=isPlaceholder,nonatomic,readonly) BOOL placeholder;              //@synthesize placeholder=_placeholder - In the implementation block
-(void)cancelFrameRequest;
-(void)_handleRequestCallback:(id)arg1 ;
-(id)initWithIndex:(unsigned long long)arg1 videoSource:(id)arg2 ;
-(void)requestFrame;
-(void)setImage:(UIImage *)arg1 ;
-(void)dealloc;
-(UIImage *)image;
-(BOOL)isPlaceholder;
@end

