/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@protocol FBWebAppActionViewSimpleDelegate;
@class UILabel, UIImageView;

@interface FBWebAppActionViewSimple : UIView {

	UILabel* _titleLabel;
	UIImageView* _alIcon;
	id<FBWebAppActionViewSimpleDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBWebAppActionViewSimpleDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithFrame:(CGRect)arg1 titleLabel:(id)arg2 style:(unsigned long long)arg3 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<FBWebAppActionViewSimpleDelegate>)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<FBWebAppActionViewSimpleDelegate>)delegate;
-(void)_handleTap:(id)arg1 ;
@end

