/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:56 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <FBSharedFramework/CKCompositeComponent.h>
#import <Messenger/FIGCardContentLandscapeAttachmentRightCompliant.h>

@class NSString;

@interface FIGAttachmentButtonComponent : CKCompositeComponent <FIGCardContentLandscapeAttachmentRightCompliant> {

	unsigned long long _style;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)newWithLabel:(id)arg1 tapAction:(const CKTypedComponentAction<>*)arg2 style:(unsigned long long)arg3 session:(id)arg4 options:(FIGAttachmentButtonOptions)arg5 ;
+(id)initialState;
-(void)updateStyle:(unsigned long long)arg1 ;
-(unsigned long long)style;
@end

