/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:52 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNComposerAutoCollapseMonitorDelegate;
#import <Messenger/Messenger-Structs.h>
@class FBTimer;

@interface MNComposerAutoCollapseMonitor : NSObject {

	long long _composerBarMode;
	BOOL _editing;
	BOOL _empty;
	BOOL _invalid;
	BOOL _scrolling;
	BOOL _selected;
	double _timeoutStartTime;
	FBTimer* _timer;
	id<MNComposerAutoCollapseMonitorDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNComposerAutoCollapseMonitorDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_checkTimeout;
-(void)_updateFlag:(BOOL*)arg1 value:(BOOL)arg2 ;
-(void)resetTimeout;
-(void)updateWithComposerBarMode:(long long)arg1 ;
-(void)updateWithTextLength:(unsigned long long)arg1 ;
-(void)textViewDidBeginEditing;
-(void)textViewDidEndEditing;
-(void)textViewDidBeginScrolling;
-(void)textViewDidEndScrolling;
-(id)init;
-(void)setDelegate:(id<MNComposerAutoCollapseMonitorDelegate>)arg1 ;
-(void)dealloc;
-(id<MNComposerAutoCollapseMonitorDelegate>)delegate;
-(void)invalidate;
-(void)textViewDidChangeSelection:(NSRange)arg1 ;
-(BOOL)_isEnabled;
-(void)_updateTimer;
@end

