/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:49 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBProviderMapData, NSMutableDictionary, MNDiscoverySurfacePerformanceLogger;

@interface MNDiscoverySurfaceUserLocationFetcherInjector : NSObject {

	FBProviderMapData* _mapData;
	NSMutableDictionary* _instances;
	MNDiscoverySurfacePerformanceLogger* _performanceLogger;
	BOOL _shouldTimeoutForLongFetch;

}
-(id)locationUpdater;
-(BOOL)shouldTimeoutForLongFetch;
-(id)initWithProviderMapData:(id)arg1 performanceLogger:(id)arg2 shouldTimeoutForLongFetch:(BOOL)arg3 ;
-(id)performanceLogger;
-(id)configManager;
-(id)userSettings;
@end

