/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:48 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@protocol MNForgotPasswordCodeEntryViewDelegate;
@class MNHeaderView, MNButton, MNStackedContainerView, MNConfirmationCodeFormView;

@interface MNForgotPasswordCodeEntryView : UIView {

	MNHeaderView* _headerView;
	MNButton* _resendCodeButton;
	MNStackedContainerView* _stackedContainerView;
	MNConfirmationCodeFormView* _confirmationCodeFormView;
	id<MNForgotPasswordCodeEntryViewDelegate> _delegate;

}

@property (nonatomic,readonly) MNStackedContainerView * stackedContainerView;                        //@synthesize stackedContainerView=_stackedContainerView - In the implementation block
@property (nonatomic,retain) MNConfirmationCodeFormView * confirmationCodeFormView;                  //@synthesize confirmationCodeFormView=_confirmationCodeFormView - In the implementation block
@property (assign,nonatomic,__weak) id<MNForgotPasswordCodeEntryViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_didTapResendCode;
-(void)setConfirmationCodeFormView:(MNConfirmationCodeFormView *)arg1 ;
-(MNStackedContainerView *)stackedContainerView;
-(MNConfirmationCodeFormView *)confirmationCodeFormView;
-(void)focusConfirmationCodeFormField;
-(id)initWithUser:(id)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<MNForgotPasswordCodeEntryViewDelegate>)arg1 ;
-(id<MNForgotPasswordCodeEntryViewDelegate>)delegate;
-(void)hideKeyboard;
@end

