/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:54 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNInAppNotificationViewDataSource.h>

@class NSString, UIView;

@interface MNInAppNotificationActionMessageDataSource : NSObject <MNInAppNotificationViewDataSource> {

	NSString* _title;
	NSString* _message;
	UIView* _imageView;
	/*^block*/id _action;

}

@property (nonatomic,copy) NSString * title;                        //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * message;                      //@synthesize message=_message - In the implementation block
@property (assign,nonatomic) UIView * imageView;                    //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,copy) id action;                               //@synthesize action=_action - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTitle:(id)arg1 message:(id)arg2 imageView:(id)arg3 actionBlock:(/*^block*/id)arg4 ;
-(void)startAction;
-(id)inAppNotificationTitle;
-(id)inAppNotificationMessage;
-(id)inAppNotificationImageView;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(id)action;
-(void)setAction:(id)arg1 ;
-(UIView *)imageView;
-(void)setMessage:(NSString *)arg1 ;
-(NSString *)message;
-(void)setImageView:(UIView *)arg1 ;
@end

