/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:28:00 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class FBAnalytics, NSObject, NSMutableDictionary;

@interface MNMessagesSyncDeltaProcessingTimeLogger : NSObject {

	FBAnalytics* _analytics;
	NSObject*<OS_dispatch_queue> _queue;
	NSMutableDictionary* _sequenceIdToBeginTimestamp;

}
-(id)initWithAnalytics:(id)arg1 queueProvider:(id)arg2 ;
-(void)beginTrackingProcessingTimeForDeltasWithMetadatas:(id)arg1 ;
-(void)markDeltaWithMetadataProcessed:(id)arg1 ;
@end

