/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:55 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/CKCompositeComponent.h>

@class MNInboxMontageItemViewModel, MNMontageItemComponentContext;

@interface MNMontageItemComponent : CKCompositeComponent {

	MNInboxMontageItemViewModel* _model;
	MNMontageItemComponentContext* _context;

}

@property (nonatomic,copy,readonly) MNInboxMontageItemViewModel * model;                  //@synthesize model=_model - In the implementation block
@property (nonatomic,copy,readonly) MNMontageItemComponentContext * context;              //@synthesize context=_context - In the implementation block
+(id)newWithModel:(id)arg1 context:(id)arg2 ;
-(MNMontageItemComponentContext *)context;
-(MNInboxMontageItemViewModel *)model;
@end

