/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:48 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewDataSource.h>
#import <FBSharedFramework/FBTableViewSectionDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@protocol FBTableViewMutating;
@class UITableViewCell, NSString;

@interface MNOptionalSingleCellDataSource : NSObject <UITableViewDataSource, FBTableViewSectionDataSource, UITableViewDelegate> {

	id<FBTableViewMutating> _tableViewMutator;
	UITableViewCell* _cellToDisplay;

}

@property (nonatomic,retain) UITableViewCell * cellToDisplay;                       //@synthesize cellToDisplay=_cellToDisplay - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) id<FBTableViewMutating> tableViewMutator;              //@synthesize tableViewMutator=_tableViewMutator - In the implementation block
@property (assign,getter=isActive,nonatomic) BOOL active; 
-(UITableViewCell *)cellToDisplay;
-(void)setCellToDisplay:(UITableViewCell *)arg1 ;
-(id<FBTableViewMutating>)tableViewMutator;
-(void)setTableViewMutator:(id<FBTableViewMutating>)arg1 ;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
@end

