/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:51 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBContainerViewController.h>
#import <Messenger/MNPaymentsFriendSearchBarViewControllerDelegate.h>
#import <FBSharedFramework/MNScrollViewScrollingListener.h>

@protocol MNPaymentsFriendPickerViewControllerDelegate;
@class MNPaymentsFriendSearchBarViewController, MNPaymentsFriendPickerConfiguration, NSArray, NSString;

@interface MNPaymentsFriendPickerViewController : FBContainerViewController <MNPaymentsFriendSearchBarViewControllerDelegate, MNScrollViewScrollingListener> {

	MNPaymentsFriendSearchBarViewController* _searchBarViewController;
	MNPaymentsFriendPickerConfiguration* _friendPickerConfiguration;
	id<MNPaymentsFriendPickerViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNPaymentsFriendPickerViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy,readonly) NSArray * pickedFriends; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_updateHeaderViewVisibility:(BOOL)arg1 ;
-(NSArray *)pickedFriends;
-(void)_handleRequestFailureWithError:(id)arg1 ;
-(double)containerTopContentInsetForFriendSearchBarViewController:(id)arg1 ;
-(void)friendSearchBarViewController:(id)arg1 didPickUser:(id)arg2 ;
-(void)friendSearchBarViewControllerWillBeginSearch:(id)arg1 ;
-(void)friendSearchBarViewControllerDidEndSearch:(id)arg1 ;
-(BOOL)friendSearchBarViewController:(id)arg1 shouldDisableCellWithContact:(id)arg2 ;
-(void)friendSearchBarViewController:(id)arg1 didDeselectContact:(id)arg2 ;
-(void)friendSearchBarViewController:(id)arg1 didSelectContact:(id)arg2 fromSearch:(BOOL)arg3 ;
-(id)initWithGraphQLService:(id)arg1 userStore:(id)arg2 threadParticipantFilter:(id)arg3 peopleCellFactory:(id)arg4 suggestedContactsRetriever:(id)arg5 friendPickerConfiguration:(id)arg6 suggestionsViewControllerCreationBlock:(/*^block*/id)arg7 ;
-(void)setDelegate:(id<MNPaymentsFriendPickerViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(void)scrollViewDidScroll:(id)arg1 ;
-(id<MNPaymentsFriendPickerViewControllerDelegate>)delegate;
-(long long)preferredStatusBarStyle;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)loadView;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)_setLoadingStatus:(BOOL)arg1 ;
@end

