/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:51 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString, NSArray;


@protocol MNPaymentsHistoryDataRetriever <NSObject>
@property (nonatomic,copy,readonly) NSString * title; 
@property (nonatomic,copy,readonly) NSString * analyticsTabName; 
@property (nonatomic,copy,readonly) NSString * contentForEmptyData; 
@property (nonatomic,readonly) BOOL hasMoreData; 
@property (getter=isLoadingData,nonatomic,readonly) BOOL loadingData; 
@property (nonatomic,copy,readonly) NSArray * loadedEdges; 
@property (assign,nonatomic,__weak) id<MNPaymentsHistoryDataRetrieverDelegate> delegate; 
@required
-(NSString *)analyticsTabName;
-(NSArray *)loadedEdges;
-(BOOL)loadMoreDataWithLimit:(unsigned long long)arg1;
-(NSString *)contentForEmptyData;
-(BOOL)hasMoreData;
-(void)setDelegate:(id)arg1;
-(id<MNPaymentsHistoryDataRetrieverDelegate>)delegate;
-(NSString *)title;
-(void)reset;
-(BOOL)isLoadingData;

@end

