/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIViewController.h>
#import <Messenger/MNPhotoEditingDrawViewDelegate.h>
#import <Messenger/FBDrawViewControllerDelegate.h>

@class MNPhotoEditingDrawView, UIView, UIImage, FBDrawViewController, NSString;

@interface MNPhotoEditingDrawViewController : UIViewController <MNPhotoEditingDrawViewDelegate, FBDrawViewControllerDelegate> {

	MNPhotoEditingDrawView* _photoEditingDrawView;
	UIView* _originalMediaView;
	UIImage* _editOverlayImage;
	FBDrawViewController* _drawViewController;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)photoEditingDrawViewDidTapUndo:(id)arg1 ;
-(BOOL)hasAddedDrawing;
-(void)setShowControls:(BOOL)arg1 ;
-(void)_updateUndoButtonVisibility;
-(id)_mergeOldEdit:(id)arg1 newEdit:(id)arg2 size:(CGSize)arg3 ;
-(void)drawViewController:(id)arg1 didChooseColor:(id)arg2 ;
-(void)drawViewControllerDidChangeUndoState:(id)arg1 ;
-(void)drawViewControllerDidStartDrawing:(id)arg1 withAnimationDuration:(double)arg2 ;
-(void)drawViewControllerDidFinishDrawing:(id)arg1 withAnimationDuration:(double)arg2 ;
-(id)initWithOriginalMediaView:(id)arg1 initialDrawEdit:(id)arg2 ;
-(id)drawEdit;
-(void)loadView;
@end

