/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:48 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class UIView, FBRichTextView;

@interface MNPictureAndLabelView : UIView {

	UIView* _picture;
	FBRichTextView* _label;
	double _verticalMargin;

}

@property (assign,nonatomic) double verticalMargin;              //@synthesize verticalMargin=_verticalMargin - In the implementation block
-(id)initWithPicture:(id)arg1 andLabel:(id)arg2 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(double)verticalMargin;
-(void)setVerticalMargin:(double)arg1 ;
@end

