/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:50 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class MNBusinessLabelViewModel, NSString;

@interface MNRideServiceLocationViewModel : FBValueObject <NSCopying> {

	MNBusinessLabelViewModel* _text;
	NSString* _imageName;

}

@property (nonatomic,copy,readonly) MNBusinessLabelViewModel * text;              //@synthesize text=_text - In the implementation block
@property (nonatomic,copy,readonly) NSString * imageName;                         //@synthesize imageName=_imageName - In the implementation block
-(id)initWithText:(id)arg1 imageName:(id)arg2 ;
-(MNBusinessLabelViewModel *)text;
-(NSString *)imageName;
@end

