/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:51 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <FBSharedFramework/FBClassInjectable.h>

@class MNRoomSuggestionImpressionTrackerInjector, NSString, NSMutableDictionary;

@interface MNRoomSuggestionImpressionTracker : NSObject <FBClassInjectable> {

	MNRoomSuggestionImpressionTrackerInjector* _injector;
	NSString* _loggingInterface;
	NSMutableDictionary* _impressionDataCache;
	long long _startIndex;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) NSString * loggingInterface;              //@synthesize loggingInterface=_loggingInterface - In the implementation block
@property (assign,nonatomic) long long startIndex;                   //@synthesize startIndex=_startIndex - In the implementation block
+(Class)injectorClass;
-(void)setLoggingInterface:(NSString *)arg1 ;
-(void)startTrackingImpressions;
-(void)stopTrackingImpressions;
-(void)willDisplayRoomSuggestion:(id)arg1 atIndex:(long long)arg2 ;
-(void)willEndDisplayRoomSuggestion:(id)arg1 atIndex:(long long)arg2 ;
-(id)impressionDataForRoomSuggestion:(id)arg1 ;
-(NSString *)loggingInterface;
-(void)_initCache;
-(void)_updateDurationAndLogEvent:(id)arg1 ;
-(id)initWithInjector:(id)arg1 ;
-(long long)startIndex;
-(void)setStartIndex:(long long)arg1 ;
@end

