/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:59 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBWebRTCHandlerListener.h>
#import <Messenger/MNSecureMessagingProtectedDataAvailabilityListening.h>

@protocol MNSecureMessagingCryptoStateLoading, OS_dispatch_queue;
@class UIApplication, NSObject, NSString;

@interface MNSecureMessagingProtectedDataAvailabilityHandler : NSObject <FBWebRTCHandlerListener, MNSecureMessagingProtectedDataAvailabilityListening> {

	id<MNSecureMessagingCryptoStateLoading> _cryptoStateLoader;
	UIApplication* _application;
	NSObject*<OS_dispatch_queue> _queue;
	BOOL _rtcCallInProgress;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)webRTCHandlerDidBeginCall;
-(void)webRTCHandlerDidEndCall;
-(void)webRTCHandlerDidStartCameraCapture;
-(void)webRTCHandlerDidEndCameraCapture;
-(id)initWithCryptoStateLoader:(id)arg1 application:(id)arg2 queue:(id)arg3 ;
-(void)protectedMessagingDataDidBecomeAvailable;
-(void)protectedMessagingDataDidBecomeUnavailable;
@end

