/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:49 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITabBarController.h>
#import <Messenger/MNContainerViewController.h>
#import <FBSharedFramework/FBClassProvidable.h>

@class NSMutableDictionary, UIView, NSString;

@interface MNTabBarController : UITabBarController <MNContainerViewController, FBClassProvidable> {

	NSMutableDictionary* _tabBarItemsOverlayViews;
	UIView* _floatingCameraCaptureButton;
	double _floatingCameraCaptureButtonBottomMargin;

}

@property (nonatomic,retain) UIView * floatingCameraCaptureButton;                        //@synthesize floatingCameraCaptureButton=_floatingCameraCaptureButton - In the implementation block
@property (assign,nonatomic) double floatingCameraCaptureButtonBottomMargin;              //@synthesize floatingCameraCaptureButtonBottomMargin=_floatingCameraCaptureButtonBottomMargin - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setTabBarItemOverlayView:(id)arg1 forViewController:(id)arg2 ;
-(void)setFloatingCameraCaptureButton:(UIView *)arg1 ;
-(void)setFloatingCameraCaptureButtonBottomMargin:(double)arg1 ;
-(id)mn_visibleContentViewControllers;
-(void)_scheduleRotationIfSupportedOrientationDifferent:(id)arg1 ;
-(void)_initTabBarItemsOverlayViewsDictionaryIfNeeded;
-(void)_clearTabBarItemsOverlayViewsDictionary;
-(id)tabBarItemOverlayViewForViewController:(id)arg1 ;
-(UIView *)floatingCameraCaptureButton;
-(double)floatingCameraCaptureButtonBottomMargin;
-(id)initWithProviderMapData:(id)arg1 ;
-(long long)preferredStatusBarStyle;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)viewWillLayoutSubviews;
-(void)viewDidLayoutSubviews;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
-(void)setViewControllers:(id)arg1 animated:(BOOL)arg2 ;
-(void)setViewControllers:(id)arg1 ;
-(void)setSelectedViewController:(id)arg1 ;
-(void)setSelectedIndex:(unsigned long long)arg1 ;
@end

