/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:47 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNBlockingGroupThreadCreatorDelegate.h>
#import <FBSharedFramework/FBClassProvidable.h>

@protocol FBProvider;
@class MNNewGroupThreadSummary, MNBlockingGroupThreadCreator, FBWebRTCCallStarter, NSString;

@interface MNVideoRoomCreateFlowCoordinator : NSObject <MNBlockingGroupThreadCreatorDelegate, FBClassProvidable> {

	MNNewGroupThreadSummary* _newGroupThreadSummary;
	unsigned long long alertDialogToken;
	id<FBProvider> _roomCreatorProvider;
	MNBlockingGroupThreadCreator* _roomCreator;
	FBWebRTCCallStarter* _callStarter;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)groupThreadCreator:(id)arg1 didFailWithError:(id)arg2 ;
-(void)groupThreadCreatorWillBeginRequest:(id)arg1 withNewGroupThreadSummary:(id)arg2 ;
-(void)groupThreadCreator:(id)arg1 didUpdateWithProgress:(double)arg2 ;
-(void)groupThreadCreator:(id)arg1 didFinishCreatingWithGroupThreadKey:(id)arg2 ;
-(void)groupThreadCreator:(id)arg1 didProfileImageUploadFailWithError:(id)arg2 forThreadKey:(id)arg3 ;
-(unsigned long long)_showAlertWithTitle:(id)arg1 message:(id)arg2 buttonTitle:(id)arg3 ;
-(void)_showLoadingDialog;
-(void)_dismissLoadingDialog;
-(void)_callThreadWithGroupThreadKey:(id)arg1 ;
-(void)presentNewVideoRoomCreateFlowWithEntryPoint:(unsigned long long*)arg1 ;
-(id)initWithProviderMapData:(id)arg1 ;
@end

