/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:58 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary;

@interface NTNativeTemplateHackyWorkaroundBecauseNSMapTableIsBuggyContainer : NSObject {

	NSDictionary* _template;

}

@property (nonatomic,__weak,readonly) NSDictionary * template;              //@synthesize template=_template - In the implementation block
-(id)initWithTemplate:(id)arg1 identifier:(const char*)arg2 ;
-(NSDictionary *)template;
@end

