/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:53 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@class UIView, UILabel, UIImageView;

@interface RTCPopAndFadeAnimationView : UIView {

	UIView* _containerView;
	UILabel* _messageLabel;
	UIImageView* _imageView;
	BOOL _isAnimating;

}
-(void)animateWithText:(id)arg1 image:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_prepareAnimationContentWithText:(id)arg1 image:(id)arg2 ;
-(id)_finalLayoutWithBounds:(CGRect)arg1 imageViewSize:(CGSize)arg2 labelSize:(CGSize)arg3 ;
-(void)_fadeAnimationWithDuration:(double)arg1 completion:(/*^block*/id)arg2 ;
-(id)_popAnimationInfoWithBounds:(CGRect)arg1 finalLayoutInfo:(id)arg2 ;
-(void)_animateWithPopAnimationInfos:(id)arg1 atIndex:(unsigned long long)arg2 completion:(/*^block*/id)arg3 ;
-(id)_animationInfosWithBounds:(CGRect)arg1 finalLayoutInfo:(id)arg2 pulseInfos:(id)arg3 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)reset;
@end

