/*
* This header is generated by classdump-dyld 1.0
* on Monday, May 8, 2017 at 12:27:49 AM Central European Summer Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/0B364788-EFE9-4CC1-B4D1-033CC2D7E2B9/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <FBSharedFramework/FBLazyInitializing.h>

@protocol FBWebRTCLogger, FBWebRTCSessionListener, FBWebRTCCallUI;
@class FBProviderMapData, FBWebRTCSession, NSString;

@interface WebRTCLazyEngine : NSObject <FBLazyInitializing> {

	FBWebRTCConfigWrapper* _configInterface;
	FBWebRTCMessageWrapper* _signalingInterface;
	FBWebRTCUIWrapper* _uiInterface;
	FBWebRTCLogWrapper* _loggingInterface;
	id<FBWebRTCLogger> _localLog;
	FBWebRTCCallMonitor* _callMonitor;
	id<FBWebRTCSessionListener> _sessionListener;
	id<FBWebRTCCallUI> _callUI;
	FBProviderMapData* _providerMap;
	BOOL _running;
	FBWebRTCSession* _session;

}

@property (nonatomic,readonly) FBWebRTCSession * session;              //@synthesize session=_session - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithSignalingMessageInterface:(FBWebRTCMessageWrapper*)arg1 uiInterface:(FBWebRTCUIWrapper*)arg2 configInterface:(FBWebRTCConfigWrapper*)arg3 loggingInterface:(FBWebRTCLogWrapper*)arg4 localLog:(id)arg5 callMonitor:(FBWebRTCCallMonitor*)arg6 engineListener:(id)arg7 callUI:(id)arg8 providerMap:(id)arg9 ;
-(FBWebRTCUIWrapper*)uiWrapper;
-(id)prepareLazyState;
-(void)dealloc;
-(FBWebRTCSession *)session;
-(BOOL)running;
@end

