/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:31:59 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@class FBUserSession, FBBrowserDebuggerTextCellView, UITableViewCell, FBBrowserDebuggerSliderCellView, FBBrowserDebuggerWhiteScreenTestCoordinator;

@interface FBBrowserDebuggerViewController : UITableViewController {

	FBUserSession* _session;
	FBBrowserDebuggerTextCellView* _URLTextFieldCell;
	UITableViewCell* _initiatePrefetchButtonCell;
	FBBrowserDebuggerTextCellView* _benchmarkInfoTextFieldCell;
	FBBrowserDebuggerSliderCellView* _whiteScreenTestLoopTimeSliderCell;
	UITableViewCell* _launchBrowserButtonCell;
	UITableViewCell* _launchBrowserWithSurfaceAboveNavBarButtonCell;
	UITableViewCell* _launchBrowserWithSurfaceBetweenNavBarAndWebViewButtonCell;
	UITableViewCell* _launchBrowserWithSurfaceAboveFooterBarButtonCell;
	UITableViewCell* _launchFBWebViewButtonCell;
	UITableViewCell* _launchWKWebViewButtonCell;
	UITableViewCell* _launchSFSafariViewControllerButtonCell;
	UITableViewCell* _prefetchingIndicatorSwitchCell;
	UITableViewCell* _resetProcessPoolButtonCell;
	UITableViewCell* _visualDebuggerSwitchCell;
	UITableViewCell* _whiteScreenTestSwitchCell;
	UITableViewCell* _whiteScreenTestPrefetchSwitchCell;
	FBBrowserDebuggerWhiteScreenTestCoordinator* browserDebuggerWhiteScreenTestCoordinator;

}
-(BOOL)fb_showNavBarSearchField;
-(void)_prefetchIndicatorsSwitchValueChanged:(id)arg1 ;
-(void)_visualDebuggerSwitchValueChanged:(id)arg1 ;
-(void)_whiteScreenTestSwitchValueChanged:(id)arg1 ;
-(void)_whiteScreenTestPrefetchSwitchValueChanged:(id)arg1 ;
-(BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(unsigned long long)supportedInterfaceOrientations;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
-(id)initWithSession:(id)arg1 ;
@end

