/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:08 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBExperimentManagerPolicy <NSObject>
@required
-(BOOL)isEmployee;
-(id)allExperimentsInCatalogAsShortDescription;
-(id)gatekeepers;
-(BOOL)sessionless;
-(void)setupDebugHelperWithExperimentCatalog:(id)arg1 debugInfoProvider:(id)arg2;
-(id)plistKey;
-(void)fetchWithExperimentCatalog:(id)arg1 withCompletionBlock:(/*^block*/id)arg2 withAllGroupsAndParameters:(BOOL)arg3 scenePath:(id)arg4;
-(double)expirationTimeIntervalInSeconds;
-(void)loadExperiments:(/*^block*/id)arg1;
-(void)loadOverrides:(/*^block*/id)arg1;
-(void)persistExperiments:(id)arg1 completionBlock:(/*^block*/id)arg2;
-(void)persistOverrides:(id)arg1 completionBlock:(/*^block*/id)arg2;
-(id)keyValueStore;

@end

