/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:14 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBAccessibilityInvalidationEventsListener.h>

@class NSString;

@interface FBFontFoundry : NSObject <FBAccessibilityInvalidationEventsListener> {

	NSString* _contentSizeCategory;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)fontForSize:(double)arg1 weight:(unsigned long long)arg2 multiplier:(double)arg3 ;
+(id)fontForStyle:(unsigned long long)arg1 weight:(unsigned long long)arg2 multiplier:(double)arg3 ;
+(id)scaledFontForSize:(double)arg1 weight:(unsigned long long)arg2 ;
+(id)scaledFontForStyle:(unsigned long long)arg1 weight:(unsigned long long)arg2 ;
+(id)fontFoundryWithCurrentCategory;
+(id)fontForStyle:(unsigned long long)arg1 weight:(unsigned long long)arg2 contentSizeCategory:(id)arg3 ;
+(id)feedFontForStyle:(long long)arg1 ;
+(id)feedFontForStyle:(long long)arg1 weight:(unsigned long long)arg2 ;
+(id)fontForSize:(double)arg1 weight:(unsigned long long)arg2 contentSizeCategory:(id)arg3 ;
+(id)fontFoundryWithCategory:(id)arg1 ;
+(id)autoupdatingMainTheadFontFoundry;
-(id)fontForStyle:(unsigned long long)arg1 weight:(unsigned long long)arg2 ;
-(void)didReceiveFontInvalidation;
-(id)feedFontForStyle:(long long)arg1 ;
-(id)feedFontForStyle:(long long)arg1 weight:(unsigned long long)arg2 ;
-(double)scaledContentSize:(double)arg1 ;
-(id)fontForSize:(double)arg1 weight:(unsigned long long)arg2 ;
-(id)initWithContentSizeCategory:(id)arg1 ;
-(void)updateContentSizeCategory:(id)arg1 ;
-(BOOL)isUsingDynamicFontSize;
@end

