/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:08 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBInstantArticleVersionFragmentBuilder <FBFragmentModelBuilderProtocol>
@required
-(id)getResult;
-(id)setGraphQLID:(id)arg1;
-(id)setDocumentCredits:(id)arg1;
-(id)setByline:(id)arg1;
-(id)setDocumentTitle:(id)arg1;
-(id)setDocumentSubtitle:(id)arg1;
-(id)setPublishTimestamp:(id)arg1;
-(id)setDocumentStyle:(id)arg1;
-(id)setCoverMedia:(id)arg1;
-(id)setDocumentBodyElements:(id)arg1;
-(id)setTrackers:(id)arg1;
-(id)setDocumentOwner:(id)arg1;
-(id)setDocumentCopyright:(id)arg1;
-(id)setDocumentKicker:(id)arg1;
-(id)setArticleCanonicalURLString:(id)arg1;
-(id)setBylineProfiles:(id)arg1;
-(id)setDocumentAuthors:(id)arg1;
-(id)setTextDirection:(id)arg1;

@end

