/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:05 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBGraphQLPaginatedConnectionController;
@class FBUserSession, NSDictionary, FBMemPageInfo;

@interface FBMemPagedDownloadController : NSObject {

	FBUserSession* _session;
	id _target;
	id<FBGraphQLPaginatedConnectionController> _connectionController;
	Class _requestClass;
	BOOL _loading;
	long long _incrementalLoadCount;
	NSDictionary* _extraQueryParameters;

}

@property (assign,nonatomic) long long incrementalLoadCount;                   //@synthesize incrementalLoadCount=_incrementalLoadCount - In the implementation block
@property (nonatomic,copy) NSDictionary * extraQueryParameters;                //@synthesize extraQueryParameters=_extraQueryParameters - In the implementation block
@property (nonatomic,copy,readonly) FBMemPageInfo * tailPageInfo; 
@property (nonatomic,readonly) long long totalCount; 
-(FBMemPageInfo *)tailPageInfo;
-(id)initWithTarget:(id)arg1 connectionModelKey:(id)arg2 requestClass:(Class)arg3 networkRequestThreshold:(unsigned long long)arg4 session:(id)arg5 ;
-(void)setIncrementalLoadCount:(long long)arg1 ;
-(void)loadWithCompletion:(/*^block*/id)arg1 ;
-(NSDictionary *)extraQueryParameters;
-(long long)incrementalLoadCount;
-(void)setExtraQueryParameters:(NSDictionary *)arg1 ;
-(id)contents;
-(BOOL)hasMoreData;
-(long long)totalCount;
@end

