/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:02 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBUserSession, FBMessengerPageSubscriptionViewModel;

@interface FBMessengerPageSubscriptionSurfaceData : NSObject {

	FBUserSession* _session;
	FBMessengerPageSubscriptionViewModel* _viewModel;

}

@property (nonatomic,readonly) FBUserSession * session;                                       //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) FBMessengerPageSubscriptionViewModel * viewModel;              //@synthesize viewModel=_viewModel - In the implementation block
-(id)initWithSession:(id)arg1 viewModel:(id)arg2 ;
-(FBMessengerPageSubscriptionViewModel *)viewModel;
-(FBUserSession *)session;
@end

