/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:15 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSArray, NSDictionary, FBMMessageExtensibleAttachment;

@interface FBMMessageAttachment : FBValueObject <NSCoding, NSCopying> {

	NSArray* _jsonAttachments;
	NSDictionary* _shareMap;
	FBMMessageExtensibleAttachment* _extensibleAttachment;

}

@property (nonatomic,copy,readonly) NSArray * jsonAttachments;                                          //@synthesize jsonAttachments=_jsonAttachments - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * shareMap;                                            //@synthesize shareMap=_shareMap - In the implementation block
@property (nonatomic,copy,readonly) FBMMessageExtensibleAttachment * extensibleAttachment;              //@synthesize extensibleAttachment=_extensibleAttachment - In the implementation block
-(unsigned long)hashDynamic;
-(BOOL)isEqualDynamic:(id)arg1 ;
-(NSArray *)jsonAttachments;
-(FBMMessageExtensibleAttachment *)extensibleAttachment;
-(NSDictionary *)shareMap;
-(id)initWithJsonAttachments:(id)arg1 shareMap:(id)arg2 extensibleAttachment:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
@end

