/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:12 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBMQTTJSONMessage, FBMQTTEncodedMessage, FBTimer;

@interface FBMQTTPublisher : NSObject {

	BOOL _forceReconnectIfDisconnected;
	BOOL _forceReconnectIfTimeout;
	BOOL _isWaitingForConnected;
	BOOL _keepRetryUntilTimeout;
	int _initialMQTTConnectState;
	FBMQTTJSONMessage* _jsonMessage;
	FBMQTTEncodedMessage* _encodedMessage;
	double _timeout;
	/*^block*/id _successBlock;
	/*^block*/id _failureBlock;
	/*^block*/id _timeoutBlock;
	double _waitIntervalForConnected;
	double _startTime;
	double _rawSendTime;
	FBTimer* _timer;

}

@property (nonatomic,readonly) double startTime;                                 //@synthesize startTime=_startTime - In the implementation block
@property (nonatomic,readonly) int initialMQTTConnectState;                      //@synthesize initialMQTTConnectState=_initialMQTTConnectState - In the implementation block
@property (assign,nonatomic) double rawSendTime;                                 //@synthesize rawSendTime=_rawSendTime - In the implementation block
@property (nonatomic,retain) FBTimer * timer;                                    //@synthesize timer=_timer - In the implementation block
@property (nonatomic,retain) FBMQTTJSONMessage * jsonMessage;                    //@synthesize jsonMessage=_jsonMessage - In the implementation block
@property (nonatomic,retain) FBMQTTEncodedMessage * encodedMessage;              //@synthesize encodedMessage=_encodedMessage - In the implementation block
@property (assign,nonatomic) double timeout;                                     //@synthesize timeout=_timeout - In the implementation block
@property (nonatomic,copy) id successBlock;                                      //@synthesize successBlock=_successBlock - In the implementation block
@property (nonatomic,copy) id failureBlock;                                      //@synthesize failureBlock=_failureBlock - In the implementation block
@property (nonatomic,copy) id timeoutBlock;                                      //@synthesize timeoutBlock=_timeoutBlock - In the implementation block
@property (assign,nonatomic) BOOL forceReconnectIfDisconnected;                  //@synthesize forceReconnectIfDisconnected=_forceReconnectIfDisconnected - In the implementation block
@property (assign,nonatomic) double waitIntervalForConnected;                    //@synthesize waitIntervalForConnected=_waitIntervalForConnected - In the implementation block
@property (assign,nonatomic) BOOL forceReconnectIfTimeout;                       //@synthesize forceReconnectIfTimeout=_forceReconnectIfTimeout - In the implementation block
@property (assign,nonatomic) BOOL isWaitingForConnected;                         //@synthesize isWaitingForConnected=_isWaitingForConnected - In the implementation block
@property (assign,nonatomic) BOOL keepRetryUntilTimeout;                         //@synthesize keepRetryUntilTimeout=_keepRetryUntilTimeout - In the implementation block
+(id)publisherWithJSONMessage:(id)arg1 ;
+(id)publisherWithEncodedMessage:(id)arg1 ;
-(void)setSuccessBlock:(id)arg1 ;
-(id)successBlock;
-(double)rawSendTime;
-(void)setTimeoutBlock:(id)arg1 ;
-(void)setForceReconnectIfDisconnected:(BOOL)arg1 ;
-(void)setForceReconnectIfTimeout:(BOOL)arg1 ;
-(void)setKeepRetryUntilTimeout:(BOOL)arg1 ;
-(void)setWaitIntervalForConnected:(double)arg1 ;
-(FBMQTTEncodedMessage *)encodedMessage;
-(FBMQTTJSONMessage *)jsonMessage;
-(int)initialMQTTConnectState;
-(BOOL)keepRetryUntilTimeout;
-(BOOL)forceReconnectIfDisconnected;
-(void)setRawSendTime:(double)arg1 ;
-(void)setEncodedMessage:(FBMQTTEncodedMessage *)arg1 ;
-(void)setIsWaitingForConnected:(BOOL)arg1 ;
-(double)waitIntervalForConnected;
-(BOOL)isWaitingForConnected;
-(BOOL)forceReconnectIfTimeout;
-(void)setJsonMessage:(FBMQTTJSONMessage *)arg1 ;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)markStart:(int)arg1 ;
-(double)startTime;
-(void)setTimer:(FBTimer *)arg1 ;
-(FBTimer *)timer;
-(void)setTimeout:(double)arg1 ;
-(id)timeoutBlock;
-(double)timeout;
-(id)failureBlock;
-(void)setFailureBlock:(id)arg1 ;
@end

