/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:12 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBObjectVisibilityTrackerDelegate;
#import <Messenger/Messenger-Structs.h>
@class NSMapTable, NSMutableDictionary;

@interface FBObjectVisibilityTracker : NSObject {

	NSMapTable* _trackedObjectsToObjectTrackingInfos;
	SCD_Struct_FB548 _delegateRespondsTo;
	NSMutableDictionary* _objectsToVisibilityKeysThatShouldNotBeTrackedAgain;
	deque<NSValue *, std::__1::allocator<NSValue *> >* _objectsThatShouldNotBeTrackedAgainInOrder;
	id<FBObjectVisibilityTrackerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<FBObjectVisibilityTrackerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)_newTrackingInfoForObject:(id)arg1 withPreviousTrackingInfo:(id)arg2 forVisibilityKey:(id)arg3 ;
-(unsigned long long)_maximumSizeOfObjectsThatShouldNotBeTrackedAgain;
-(void)startTrackingObject:(id)arg1 ;
-(void)stopTrackingObject:(id)arg1 ;
-(void)updateVisibilityStatesForAllTrackedObjects;
-(void)setDelegate:(id<FBObjectVisibilityTrackerDelegate>)arg1 ;
-(id)init;
-(id<FBObjectVisibilityTrackerDelegate>)delegate;
@end

