/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:05 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSURL;

@interface FBPlaylistRequest : NSObject {

	/*^block*/id _responseBlock;
	NSString* _videoID;
	NSString* _trackerID;
	long long _initalbytestart;
	NSURL* _requestUrl;

}
-(void)respond:(id)arg1 ;
-(id)_translatePlaylistData:(id)arg1 ;
-(id)initWithResponse:(/*^block*/id)arg1 videoID:(id)arg2 trackerID:(id)arg3 url:(id)arg4 ;
-(void)respondWithError:(id)arg1 ;
@end

