/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:00 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBPlatformActionOperationDelegate
@required
-(void)platformActionOperation:(id)arg1 didFailWithErrorCode:(unsigned long long)arg2 errorMessage:(id)arg3 errorResponse:(id)arg4;
-(void)platformActionOperationDidComplete:(id)arg1;

@end

