/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:31:56 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBWebRtcCallCamper.h>

@class UILocalNotification;

@interface FBWebRtcCallerCallCamper : FBWebRtcCallCamper {

	BOOL actionIsDone;
	double lastSeenInterval;
	UILocalNotification* _currentNotification;

}

@property (nonatomic,retain) UILocalNotification * currentNotification;              //@synthesize currentNotification=_currentNotification - In the implementation block
-(id)initWithPeer:(id)arg1 startTime:(double)arg2 readyDelay:(double)arg3 waitTime:(double)arg4 ;
-(void)runCampAction;
-(void)abortCampAction;
-(void)onReceivedPresenceMessageReachable:(BOOL)arg1 seenDate:(id)arg2 ;
-(BOOL)requireVoipIdle;
-(BOOL)requirePstnIdle;
-(BOOL)requireUserPresence;
-(BOOL)_peerIsReachable;
-(void)_postLocalNotification;
-(void)_abortCurrentLocalNotification;
-(void)_checkLocalNotificationExpired:(id)arg1 ;
-(BOOL)isReady;
-(void)scheduleLocalNotification:(id)arg1 ;
-(void)_applicationDidBecomeActive:(id)arg1 ;
-(BOOL)isDone;
-(UILocalNotification *)currentNotification;
-(void)setCurrentNotification:(UILocalNotification *)arg1 ;
@end

