/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:11 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBWhistleDelegate <NSObject>
@required
-(void)onConnectSent;
-(void)onConnSuccess:(id)arg1;
-(void)onConnFailure:(id)arg1;
-(void)onPingResponseTimeout;
-(void)onPublishWithTopic:(id)arg1 messageId:(id)arg2 qos:(int)arg3 payload:(id)arg4 receiveTime:(double)arg5;
-(void)onPublishSentWithMessageId:(id)arg1 context:(id)arg2;
-(void)onPublishFailedWithContext:(id)arg1 error:(id)arg2;
-(void)onPubAckWithMessageId:(id)arg1;
-(void)onSubAckWithMessageId:(id)arg1;
-(void)onPingRequestSent;
-(void)onPingResponse;
-(void)onError:(id)arg1;

@end

