/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:16 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface GLProgram : NSObject {

	NSMutableArray* attributes;
	NSMutableArray* uniforms;
	unsigned vertShader;
	unsigned fragShader;
	BOOL _initialized;
	unsigned _program;

}

@property (assign,nonatomic) BOOL initialized;                //@synthesize initialized=_initialized - In the implementation block
@property (nonatomic,readonly) unsigned program;              //@synthesize program=_program - In the implementation block
-(unsigned)uniformIndex:(id)arg1 ;
-(id)vertexShaderLog;
-(id)fragmentShaderLog;
-(id)programLog;
-(id)initWithVertexShaderString:(id)arg1 fragmentShaderString:(id)arg2 ;
-(unsigned)attributeIndex:(id)arg1 ;
-(BOOL)compileShader:(unsigned*)arg1 type:(unsigned)arg2 string:(id)arg3 ;
-(id)logForOpenGLObject:(unsigned)arg1 infoCallback:(/*function pointer*/void*)arg2 logFunc:(/*function pointer*/void*)arg3 ;
-(id)initWithVertexShaderString:(id)arg1 fragmentShaderFilename:(id)arg2 ;
-(id)initWithVertexShaderFilename:(id)arg1 fragmentShaderFilename:(id)arg2 ;
-(void)dealloc;
-(void)use;
-(void)validate;
-(BOOL)link;
-(void)addAttribute:(id)arg1 ;
-(BOOL)initialized;
-(unsigned)program;
-(void)setInitialized:(BOOL)arg1 ;
@end

