/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:00 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBFriendListDeltaMonitorListener.h>

@protocol FBFriendListDeltaMonitorListener;
@class NSMutableArray, NSArray, NSString;

@interface MNFriendListDeltaMonitorListener : NSObject <FBFriendListDeltaMonitorListener> {

	NSMutableArray* _queuedAddedFriends;
	NSMutableArray* _queuedRemovedFriends;
	id<FBFriendListDeltaMonitorListener> _delegate;

}

@property (nonatomic,copy,readonly) NSArray * queuedAddedFriends; 
@property (nonatomic,copy,readonly) NSArray * queuedRemovedFriends; 
@property (assign,nonatomic,__weak) id<FBFriendListDeltaMonitorListener> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(NSArray *)queuedRemovedFriends;
-(NSArray *)queuedAddedFriends;
-(void)didAddFriends:(id)arg1 ;
-(void)didRemoveFriends:(id)arg1 ;
-(void)setDelegate:(id<FBFriendListDeltaMonitorListener>)arg1 ;
-(id)init;
-(id<FBFriendListDeltaMonitorListener>)delegate;
@end

