/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:32:02 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDictionary, NSMutableSet;

@interface MNMessagesSyncThreadPrepareJobExecutorCompletionHelper : NSObject {

	NSDictionary* _jobsBySyncedThreadKey;
	NSMutableSet* _syncedThreadKeysCompletedCalledFor;
	/*^block*/id _completedBlock;

}
-(id)initWithThreadPreparationJobs:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)successfulResponseReceivedForThreadKeys:(id)arg1 ;
-(void)threadRequestFailedWithError:(id)arg1 ;
-(void)preliminaryResponseReceivedFromLocalCacheForThreadKeys:(id)arg1 ;
-(void)_invokeSuccessfulCompletionIfPossibleForThreadKeys:(id)arg1 isPrelim:(BOOL)arg2 ;
@end

