/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:31:56 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBMCustomDictionaryStoreDelegate.h>
#import <Messenger/MNMontageRecentForwardedMessageStoreWriting.h>
#import <Messenger/MNMontageRecentForwardedMessageStoreReading.h>

@protocol OS_dispatch_queue;
@class FBMCustomDictionaryStore, NSObject, MNMontageRecentForwardedMessageStoreListenerAnnouncer, NSDictionary, NSString;

@interface MNMontageRecentForwardedMessageStore : NSObject <FBMCustomDictionaryStoreDelegate, MNMontageRecentForwardedMessageStoreWriting, MNMontageRecentForwardedMessageStoreReading> {

	FBMCustomDictionaryStore* _diskHandler;
	NSObject*<OS_dispatch_queue> _queue;
	MNMontageRecentForwardedMessageStoreListenerAnnouncer* _announcer;
	NSDictionary* _recentForwardedMessageKeys;

}

@property (copy) NSDictionary * recentForwardedMessageKeys;              //@synthesize recentForwardedMessageKeys=_recentForwardedMessageKeys - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)recentForwardedMessageKeyForThreadKey:(id)arg1 ;
-(NSDictionary *)recentForwardedMessageKeys;
-(void)setRecentForwardedMessageKeys:(NSDictionary *)arg1 ;
-(void)_scheduleWriteToDatabase;
-(void)customDictionaryStore:(id)arg1 didRestoreStateFromDisk:(id)arg2 ;
-(void)setRecentForwardedMessageKey:(id)arg1 forThreadKey:(id)arg2 ;
-(id)initWithMessagingStore:(id)arg1 messagingStoreDelayer:(id)arg2 queue:(id)arg3 ;
-(void)beginDiskRestore;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
@end

