/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:31:56 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface MNPaymentsThemeLayoutConfiguration : FBValueObject <NSCopying> {

	BOOL _isBlankPageEnabled;
	double _themePageExtraPageSpacing;
	unsigned long long _themeSection;

}

@property (nonatomic,readonly) BOOL isBlankPageEnabled;                       //@synthesize isBlankPageEnabled=_isBlankPageEnabled - In the implementation block
@property (nonatomic,readonly) double themePageExtraPageSpacing;              //@synthesize themePageExtraPageSpacing=_themePageExtraPageSpacing - In the implementation block
@property (nonatomic,readonly) unsigned long long themeSection;               //@synthesize themeSection=_themeSection - In the implementation block
-(BOOL)isBlankPageEnabled;
-(double)themePageExtraPageSpacing;
-(unsigned long long)themeSection;
-(id)initWithIsBlankPageEnabled:(BOOL)arg1 themePageExtraPageSpacing:(double)arg2 themeSection:(unsigned long long)arg3 ;
@end

