/*
* This header is generated by classdump-dyld 1.0
* on Saturday, December 3, 2016 at 12:31:53 PM Central European Standard Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/51214F70-E877-4284-9DAC-5D8552407255/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>

@protocol MNSyncingContactsViewDelegate;
@class UIImageView, UILabel;

@interface MNSyncingContactsView : UIView {

	id<MNSyncingContactsViewDelegate> _delegate;
	UIImageView* _stickerView;
	UILabel* _textLabel;

}

@property (nonatomic,retain) UIImageView * stickerView;                                      //@synthesize stickerView=_stickerView - In the implementation block
@property (nonatomic,retain) UILabel * textLabel;                                            //@synthesize textLabel=_textLabel - In the implementation block
@property (assign,nonatomic,__weak) id<MNSyncingContactsViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_completeSyncingContactView;
-(void)showBeforeAutoDismiss;
-(UIImageView *)stickerView;
-(void)setStickerView:(UIImageView *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<MNSyncingContactsViewDelegate>)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(id<MNSyncingContactsViewDelegate>)delegate;
-(UILabel *)textLabel;
-(void)setTextLabel:(UILabel *)arg1 ;
@end

