/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:50 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBGraphQLConnectionStoreSimpleDeleteController.h>

@class FBUserSession, NSMapTable, NSMutableArray, FBAlbumStoreManagerListenerAnnouncer, FBAlbumStoreEdgeHandler, NSString;

@interface FBAlbumStoreManager : NSObject <FBGraphQLConnectionStoreSimpleDeleteController> {

	FBUserSession* _session;
	NSMapTable* _storeMap;
	NSMutableArray* _deletedFilters;
	FBAlbumStoreManagerListenerAnnouncer* _announcer;
	FBAlbumStoreEdgeHandler* _edgeHandler;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_applyDeleteFilters;
-(id)_edgeStoreWithInitialNodes:(id)arg1 requestProvider:(id)arg2 ;
-(id)_allDeletedAlbumIds;
-(void)deleteAlbumsWithIDs:(id)arg1 ;
-(void)graphQLConnectionStoreSimple:(id)arg1 deleteNodesWithGraphQLIDs:(id)arg2 ;
-(id)albumStoreWithRequestProvider:(id)arg1 networkRequestThresholdInSeconds:(int)arg2 alwaysUseFirstCachedResponse:(BOOL)arg3 initialAlbums:(id)arg4 ;
-(id)initWithSession:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
-(void)addListener:(id)arg1 ;
@end

