/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:26:02 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UITableViewCell, NSString;

@interface FBBugReportInitialForkViewTinesTableViewCellInfo : NSObject {

	int _cellHeight;
	UITableViewCell* _cell;
	NSString* _selectorName;

}

@property (nonatomic,retain) UITableViewCell * cell;              //@synthesize cell=_cell - In the implementation block
@property (assign) int cellHeight;                                //@synthesize cellHeight=_cellHeight - In the implementation block
@property (nonatomic,copy) NSString * selectorName;               //@synthesize selectorName=_selectorName - In the implementation block
-(void)setCellHeight:(int)arg1 ;
-(id)initWithCell:(id)arg1 cellHeight:(int)arg2 selectorName:(id)arg3 ;
-(UITableViewCell *)cell;
-(void)setCell:(UITableViewCell *)arg1 ;
-(int)cellHeight;
-(NSString *)selectorName;
-(void)setSelectorName:(NSString *)arg1 ;
@end

