/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:52 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class FBPhotoAssetEdits, NSString, UIImage;


@protocol FBEditableIdentifiablePhoto <NSObject>
@property (nonatomic,retain) FBPhotoAssetEdits * edits; 
@property (nonatomic,copy,readonly) NSString * assetID; 
@property (nonatomic,retain) UIImage * displayImage; 
@property (nonatomic,retain) UIImage * displayThumbnailImage; 
@required
-(NSString *)assetID;
-(FBPhotoAssetEdits *)edits;
-(void)setDisplayImage:(id)arg1;
-(void)setEdits:(id)arg1;
-(void)setDisplayThumbnailImage:(id)arg1;
-(UIImage *)displayThumbnailImage;
-(UIImage *)displayImage;

@end

