/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:26:02 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBGraphQLConnectionStoreStateModifying;
@interface FBGraphQLConnectionStoreAsynchronousModificationPair : NSObject {

	id<FBGraphQLConnectionStoreStateModifying> _modification;
	/*^block*/id _callback;

}

@property (nonatomic,readonly) id<FBGraphQLConnectionStoreStateModifying> modification;              //@synthesize modification=_modification - In the implementation block
@property (nonatomic,readonly) id callback;                                                          //@synthesize callback=_callback - In the implementation block
-(id)initWithModification:(id)arg1 callback:(/*^block*/id)arg2 ;
-(id)callback;
-(id<FBGraphQLConnectionStoreStateModifying>)modification;
@end

