/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:26:04 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBDataDeserializing.h>

@class NSSet;

@interface FBJSONResponseDeserializer : NSObject <FBDataDeserializing> {

	NSSet* _expectedTypes;

}
+(id)setForExpectedTypeEnum:(long long)arg1 ;
-(id)initWithExpectedTypes:(long long)arg1 ;
-(id)_parseJSONDataFragment:(id)arg1 error:(id*)arg2 ;
-(void)deserialize:(id)arg1 responseProcessor:(id)arg2 completionCallback:(/*^block*/id)arg3 failureCallback:(/*^block*/id)arg4 ;
-(id)description;
@end

