/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:53 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSString, FBAssetLocationInfo, NSDictionary;

@interface FBMagicStoryCollectionBuilder : NSObject {

	NSArray* _assets;
	NSString* _uniqueId;
	unsigned long long _type;
	FBAssetLocationInfo* _locationInfo;
	double _classifierScore;
	NSDictionary* _classifierLoggingData;

}
+(id)magicStoryCollection;
+(id)magicStoryCollectionFromExistingMagicStoryCollection:(id)arg1 ;
-(id)withType:(unsigned long long)arg1 ;
-(id)withAssets:(id)arg1 ;
-(id)withUniqueId:(id)arg1 ;
-(id)withLocationInfo:(id)arg1 ;
-(id)withClassifierScore:(double)arg1 ;
-(id)withClassifierLoggingData:(id)arg1 ;
-(id)build;
@end

