/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:49 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol FBMIncrementalPersistenceCoordinatorObserving <NSObject>
@required
-(void)incrementalPersistenceCoordinator:(id)arg1 didFinishJobQueue:(id)arg2 fromSyncProtocolWithSequenceId:(long long)arg3;
-(void)incrementalPersistenceCoordinator:(id)arg1 didFailRunningJobQueue:(id)arg2 fromSyncProtocolWithSequenceId:(long long)arg3 withError:(id)arg4;
-(void)incrementalPersistenceCoordinator:(id)arg1 didFinishNonSyncProtocolJobQueue:(id)arg2;
-(void)incrementalPersistenceCoordinator:(id)arg1 didFailRunningNonSyncProtocolJobQueue:(id)arg2 withError:(id)arg3;

@end

