/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:55 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSURL;

@interface FBPlaylistRequest : NSObject {

	/*^block*/id _responseBlock;
	NSString* _videoID;
	NSString* _trackerID;
	long long _initalbytestart;
	NSURL* _requestUrl;

}
-(id)_translatePlaylistData:(id)arg1 ;
-(id)initWithResponse:(/*^block*/id)arg1 videoID:(id)arg2 trackerID:(id)arg3 url:(id)arg4 ;
-(void)respond:(id)arg1 ;
-(void)respondWithError:(id)arg1 ;
@end

