/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:50 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class FBMemRapidReportingPrompt, FBMemSubmitRapidReportResponsePayload;

@interface FBRapidReportingModel : NSObject {

	int _status;
	int _submitStatus;
	FBMemRapidReportingPrompt* _metadata;
	FBMemSubmitRapidReportResponsePayload* _submitPayload;

}

@property (nonatomic,readonly) int status;                                                              //@synthesize status=_status - In the implementation block
@property (nonatomic,copy,readonly) FBMemRapidReportingPrompt * metadata;                               //@synthesize metadata=_metadata - In the implementation block
@property (nonatomic,readonly) int submitStatus;                                                        //@synthesize submitStatus=_submitStatus - In the implementation block
@property (nonatomic,copy,readonly) FBMemSubmitRapidReportResponsePayload * submitPayload;              //@synthesize submitPayload=_submitPayload - In the implementation block
-(id)initWithStatus:(int)arg1 metadata:(id)arg2 submitStatus:(int)arg3 confirmationPrompt:(id)arg4 ;
-(int)submitStatus;
-(FBMemSubmitRapidReportResponsePayload *)submitPayload;
-(int)status;
-(FBMemRapidReportingPrompt *)metadata;
@end

