/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:26:01 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <Messenger/CKComponent.h>

@class NSAttributedString;

@interface FBRichTextComponent : CKComponent {

	NSAttributedString* _attributedString;
	FBRichTextComponentStyle _style;
	SEL _action;

}
+(id)newWithView:(const CKComponentViewConfiguration*)arg1 size:(const CKComponentSize*)arg2 ;
+(id)newWithAttributedString:(id)arg1 style:(const FBRichTextComponentStyle*)arg2 action:(SEL)arg3 attributes:(const unordered_map<CKComponentViewAttribute, CKBoxedValue, std::__1::hash<CKComponentViewAttribute>, std::__1::equal_to<CKComponentViewAttribute>, std::__1::allocator<std::__1::pair<const CKComponentViewAttribute, CKBoxedValue> > >*)arg4 accessibilityContext:(const FBRichTextComponentAccessibilityContext*)arg5 size:(const CKComponentSize*)arg6 ;
-(CKComponentLayout*)computeLayoutThatFits:(CKSizeRange)arg1 ;
-(id)forceTouchContextAtPoint:(CGPoint)arg1 inSourceView:(id)arg2 ;
-(void)sendActionWithContext:(id)arg1 ;
@end

