/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:57 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSAttributedString, FBRichTextView;


@protocol FBTextLabeling
@property (nonatomic,copy) NSAttributedString * text; 
@property (nonatomic,readonly) FBRichTextView * attributedLabel; 
@property (assign,nonatomic) long long verticalTextAlignment; 
@property (nonatomic,readonly) CGRect textLayoutFrame; 
@required
-(FBRichTextView *)attributedLabel;
-(CGRect)textLayoutFrame;
-(long long)verticalTextAlignment;
-(void)setVerticalTextAlignment:(long long)arg1;
-(NSAttributedString *)text;
-(void)setText:(id)arg1;

@end

