/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:48 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIView.h>
#import <Messenger/FBSystemAudioSessionManagerListener.h>
#import <Messenger/FBNuxStepChainControllerDelegate.h>
#import <Messenger/FBVideoPluginView.h>

@class UIView, UIButton, FBVideoSoundToggleExperimentContext, FBUserSession, NSDate, FBNuxController, FBVideoPlaybackController, NSString;

@interface FBVideoSoundTogglePlugin : UIView <FBSystemAudioSessionManagerListener, FBNuxStepChainControllerDelegate, FBVideoPluginView> {

	CGRect _videoFrame;
	UIView* _pluginBackgroundView;
	UIView* _glyphBackgroundView;
	UIButton* _glyphView;
	FBVideoSoundToggleExperimentContext* _context;
	FBUserSession* _session;
	NSDate* _tooltipStartTime;
	double _toggleViewPointY;
	BOOL _isActive;
	FBNuxController* _tooltipController;
	float _lastKnownVolume;
	BOOL _isSoundON;
	FBVideoPlaybackController* _videoController;

}

@property (assign,nonatomic) BOOL isSoundON;                                                  //@synthesize isSoundON=_isSoundON - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic) CGRect videoFrame;                                               //@synthesize videoFrame=_videoFrame - In the implementation block
@property (assign,nonatomic,__weak) FBVideoPlaybackController * videoController;              //@synthesize videoController=_videoController - In the implementation block
@property (nonatomic,readonly) unsigned long long visibilityOptions; 
-(void)videoPlaybackControllerDidStartPlayback:(id)arg1 ;
-(void)stepChainControllerDidEnd:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 session:(id)arg2 ;
-(void)audioSessionManagerUpdatedAudioSession:(id)arg1 ;
-(void)audioSessionManagerNotedRouteChange:(id)arg1 ;
-(CGRect)videoFrame;
-(void)setVideoFrame:(CGRect)arg1 ;
-(unsigned long long)visibilityOptions;
-(void)videoPlaybackController:(id)arg1 didUpdatePlaybackTime:(double)arg2 ;
-(void)_handleToggle:(id)arg1 ;
-(void)setSoundOnSetting:(long long)arg1 ;
-(void)setIsSoundON:(BOOL)arg1 ;
-(BOOL)_currentSoundOnSetting;
-(void)_handleVolumeChange:(id)arg1 ;
-(void)_reloadSoundOnPlugin:(id)arg1 ;
-(void)_refreshSoundSetting:(id)arg1 ;
-(void)_maybeDisplayNUX;
-(BOOL)_isCurrentSettingUnset;
-(BOOL)_shouldTurnOnForUnset;
-(void)_displayNUX;
-(void)sizeToFits;
-(void)setActive;
-(BOOL)isSoundON;
-(void)dealloc;
-(void)setHidden:(BOOL)arg1 ;
-(void)layoutSubviews;
-(void)invalidate;
-(FBVideoPlaybackController *)videoController;
-(void)setVideoController:(FBVideoPlaybackController *)arg1 ;
@end

