/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:56 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSURL;

@interface MNAdaptiveImageDownloaderStreamingConfiguration : FBValueObject <NSCopying> {

	NSURL* _url;
	unsigned long long _imageFlags;

}

@property (nonatomic,copy,readonly) NSURL * url;                           //@synthesize url=_url - In the implementation block
@property (nonatomic,readonly) unsigned long long imageFlags;              //@synthesize imageFlags=_imageFlags - In the implementation block
-(unsigned long long)imageFlags;
-(id)initWithUrl:(id)arg1 imageFlags:(unsigned long long)arg2 ;
-(NSURL *)url;
@end

