/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:46 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/Messenger-Structs.h>
#import <UIKit/UIWindow.h>
#import <Messenger/FBKeyCommandResponder.h>

@class FBKeyCommandHandler, NSString;

@interface MNApplicationWindow : UIWindow <FBKeyCommandResponder> {

	FBKeyCommandHandler* _keyCommandHandler;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 keyCommandHandler:(id)arg2 ;
-(void)handleKeyCommandAction:(id)arg1 ;
-(void)motionEnded:(long long)arg1 withEvent:(id)arg2 ;
-(id)keyCommands;
@end

