/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:48 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString, FBStringWithRedactedDescription, MNComposerSearchBar;


@protocol MNComposerSearchBarConfiguring <NSObject>
@property (assign,nonatomic,__weak) id<MNComposerSearchBarDelegate> delegate; 
@property (assign,nonatomic) UIEdgeInsets edgeInsets; 
@property (nonatomic,copy) NSString * placeholderText; 
@property (nonatomic,copy) FBStringWithRedactedDescription * text; 
@property (nonatomic,readonly) MNComposerSearchBar * composerSearchBar; 
@required
-(MNComposerSearchBar *)composerSearchBar;
-(void)setCancelButtonTitleColor:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id<MNComposerSearchBarDelegate>)delegate;
-(FBStringWithRedactedDescription *)text;
-(void)setText:(id)arg1;
-(UIEdgeInsets)edgeInsets;
-(void)setEdgeInsets:(UIEdgeInsets)arg1;
-(NSString *)placeholderText;
-(void)setPlaceholderText:(id)arg1;

@end

