/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:49 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Messenger/MNMessageLiveLocationTrayMapViewControllerDelegate.h>
#import <Messenger/MNMessageLiveLocationAuthorizationManagerListener.h>
#import <Messenger/MNMessageLiveLocationUpdaterListener.h>
#import <Messenger/MNThreadSummarySubscribing.h>

@protocol FBLocationManagerSubscription, MNMessageLiveLocationTrayViewControllerDelegate;
@class FBUserSession, MNMessageLiveLocationUpdater, MNMessageLiveLocationConfigManager, MNThreadStore, MNThreadSummarySubscribingAnnouncer, MNMessageLiveLocationAnalyticsLogger, MNMessageLiveLocationTrayView, MNMessageLiveLocationTrayMapViewController, CLLocation, FBMSyncedThreadKey, NSSet, MNMessageLiveLocationAuthorizationManager, MNLoadingView, NSString;

@interface MNMessageLiveLocationTrayViewController : UIViewController <MNMessageLiveLocationTrayMapViewControllerDelegate, MNMessageLiveLocationAuthorizationManagerListener, MNMessageLiveLocationUpdaterListener, MNThreadSummarySubscribing> {

	FBUserSession* _session;
	MNMessageLiveLocationUpdater* _messageLiveLocationUpdater;
	MNMessageLiveLocationConfigManager* _configManager;
	MNThreadStore* _threadStore;
	MNThreadSummarySubscribingAnnouncer* _threadSummarySubscribingAnnouncer;
	MNMessageLiveLocationAnalyticsLogger* _analyticsLogger;
	MNMessageLiveLocationTrayView* _trayView;
	MNMessageLiveLocationTrayMapViewController* _trayMapViewController;
	CLLocation* _initialUserLocation;
	FBMSyncedThreadKey* _threadKey;
	NSSet* _liveLocations;
	BOOL _hasFetchedLiveLocations;
	MNMessageLiveLocationAuthorizationManager* _authorizationManager;
	id<FBLocationManagerSubscription> _locationManagerToken;
	unsigned long long _threadStoreRequestId;
	MNLoadingView* _loadingView;
	id<MNMessageLiveLocationTrayViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<MNMessageLiveLocationTrayViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)didApplyUpdates:(id)arg1 toThreadSummary:(id)arg2 ;
-(void)didDeleteThreadWithKey:(id)arg1 ;
-(void)didReplaceThreadSummary:(id)arg1 withThreadSummary:(id)arg2 forThreadKey:(id)arg3 ;
-(void)didPurgeSummary:(id)arg1 ;
-(void)didPurgeAllThreadSummaries;
-(void)_cancelThreadStoreRequest;
-(void)_locationAuthorizationDidChangeOnMainThreadToStatus:(long long)arg1 ;
-(void)startedSendingLocationUpdatesForThreadKey:(id)arg1 offlineThreadingId:(id)arg2 ;
-(void)stoppedSendingLocationUpdatesForThreadKey:(id)arg1 offlineThreadingId:(id)arg2 ;
-(void)locationAuthorizationStatusDidChangeToStatus:(long long)arg1 ;
-(id)initWithSession:(id)arg1 messageLiveLocationUpdater:(id)arg2 configManager:(id)arg3 threadStore:(id)arg4 threadSummarySubscribingAnnouncer:(id)arg5 ;
-(id)_nonViewerLiveLocations;
-(void)messageLiveLocationTrayMapViewController:(id)arg1 startSendingLiveLocation:(id)arg2 ;
-(void)messageLiveLocationTrayMapViewControllerStopSendingLiveLocation:(id)arg1 ;
-(void)_resetThreadSpecificState;
-(void)_initializeLoadingViewIfNeeded;
-(void)_setTrayViewModelToShowingMapWithIsSendingLiveLocation:(BOOL)arg1 ;
-(void)_fetchAllDataIfNecessaryAndUpdateView;
-(void)_initializeTrayMapViewControllerIfNeeded;
-(id)_viewerLiveLocation;
-(void)_fetchInitialUserLocationIfNecessaryAndUpdateView;
-(void)_fetchLiveLocationsIfNecessaryWithCompletionBlock:(/*^block*/id)arg1 ;
-(void)_setTrayViewModelToLoading;
-(void)_didReceiveThreadStoreResponseWithThreadSummary:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(void)_didReceiveLiveLocations:(id)arg1 ;
-(void)_setTrayViewModelToShowingMap;
-(void)_requestAlwaysLocationPermissionIfNecessary;
-(void)_didReceiveLocationUpdateWithLocation:(id)arg1 error:(id)arg2 ;
-(void)_didReceiveThreadUpdateWithThreadKey:(id)arg1 liveLocations:(id)arg2 ;
-(void)setDelegate:(id<MNMessageLiveLocationTrayViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(id<MNMessageLiveLocationTrayViewControllerDelegate>)delegate;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
@end

