/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:45 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MNNewThreadViewControllerDelegate <NSObject>
@required
-(void)newThreadViewController:(id)arg1 navigateToThreadWithLocalThreadQuery:(id)arg2 isFlowersBorderModeEnabled:(BOOL)arg3 animated:(BOOL)arg4;
-(void)newThreadViewControllerDidCancel:(id)arg1;
-(void)newThreadViewControllerDidClickOnNewGroup:(id)arg1 withPickedContacts:(id)arg2;
-(BOOL)newThreadViewControllerCanShowKeyboard:(id)arg1;
-(void)newThreadViewControllerDidPressSecretButton:(id)arg1;

@end

