/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:52 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSDictionary, MNPendingThreadCreationInfo;

@interface MNPendingThread : FBValueObject <NSCopying> {

	BOOL _isGroupThread;
	BOOL _isFailed;
	NSString* _offlineId;
	NSDictionary* _inviteeByUserId;
	NSDictionary* _inviteeByPhoneNumber;
	MNPendingThreadCreationInfo* _creationInfo;
	unsigned long long _timestamp;

}

@property (nonatomic,copy,readonly) NSString * offlineId;                                    //@synthesize offlineId=_offlineId - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * inviteeByUserId;                          //@synthesize inviteeByUserId=_inviteeByUserId - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * inviteeByPhoneNumber;                     //@synthesize inviteeByPhoneNumber=_inviteeByPhoneNumber - In the implementation block
@property (nonatomic,copy,readonly) MNPendingThreadCreationInfo * creationInfo;              //@synthesize creationInfo=_creationInfo - In the implementation block
@property (nonatomic,readonly) BOOL isGroupThread;                                           //@synthesize isGroupThread=_isGroupThread - In the implementation block
@property (nonatomic,readonly) unsigned long long timestamp;                                 //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL isFailed;                                                //@synthesize isFailed=_isFailed - In the implementation block
-(MNPendingThreadCreationInfo *)creationInfo;
-(NSString *)offlineId;
-(NSDictionary *)inviteeByUserId;
-(BOOL)isGroupThread;
-(id)initWithOfflineId:(id)arg1 inviteeByUserId:(id)arg2 inviteeByPhoneNumber:(id)arg3 creationInfo:(id)arg4 isGroupThread:(BOOL)arg5 timestamp:(unsigned long long)arg6 isFailed:(BOOL)arg7 ;
-(NSDictionary *)inviteeByPhoneNumber;
-(BOOL)isFailed;
-(unsigned long long)timestamp;
@end

