/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:46 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/FBValueObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSArray, FBUserStorageServerKey;

@interface MNPendingAccount : FBValueObject <NSCopying> {

	NSString* _userID;
	NSString* _machineID;
	NSString* _accessToken;
	NSArray* _cookies;
	FBUserStorageServerKey* _storageServerKey;
	NSString* _analyticsModule;

}

@property (nonatomic,copy,readonly) NSString * userID;                                      //@synthesize userID=_userID - In the implementation block
@property (nonatomic,copy,readonly) NSString * machineID;                                   //@synthesize machineID=_machineID - In the implementation block
@property (nonatomic,copy,readonly) NSString * accessToken;                                 //@synthesize accessToken=_accessToken - In the implementation block
@property (nonatomic,copy,readonly) NSArray * cookies;                                      //@synthesize cookies=_cookies - In the implementation block
@property (nonatomic,copy,readonly) FBUserStorageServerKey * storageServerKey;              //@synthesize storageServerKey=_storageServerKey - In the implementation block
@property (nonatomic,copy,readonly) NSString * analyticsModule;                             //@synthesize analyticsModule=_analyticsModule - In the implementation block
-(NSString *)analyticsModule;
-(id)initWithUserID:(id)arg1 machineID:(id)arg2 accessToken:(id)arg3 cookies:(id)arg4 storageServerKey:(id)arg5 analyticsModule:(id)arg6 ;
-(FBUserStorageServerKey *)storageServerKey;
-(NSArray *)cookies;
-(NSString *)machineID;
-(NSString *)userID;
-(NSString *)accessToken;
@end

