/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:25:48 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/MNFriendListModelControllerDelegate.h>
#import <Messenger/MNViewModelUpdateMonitoring.h>

@protocol MNFriendListModelController, MNFriendListModelControllerDelegate, MNViewModelUpdating;
@class NSArray, NSString;

@interface MNTopPHATContactsRetriever : NSObject <MNFriendListModelControllerDelegate, MNViewModelUpdateMonitoring> {

	id<MNFriendListModelController> _friendListModelController;
	id<MNFriendListModelControllerDelegate> _dispatchedFriendListModelControllerDelegate;
	id<MNViewModelUpdating> _updater;
	NSArray* _phatUsers;

}

@property (nonatomic,copy,readonly) NSArray * phatUsers;              //@synthesize phatUsers=_phatUsers - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)friendListModelController:(id)arg1 didLoadConversationPeople:(id)arg2 ;
-(void)configureWithUpdater:(id)arg1 ;
-(NSArray *)phatUsers;
-(id)initWithFriendListModelController:(id)arg1 queue:(id)arg2 ;
-(void)startRetrieving;
-(void)cancel;
@end

