/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 18, 2016 at 3:26:07 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/FF4BCEA7-3F74-4B1C-9F1F-FFFFF37A922E/Messenger.app/Messenger
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Messenger/OCMockObject.h>

@class NSMutableDictionary;

@interface OCClassMockObject : OCMockObject {

	Class mockedClass;
	NSMutableDictionary* replacedClassMethods;

}
+(void)forgetMockForClass:(Class)arg1 ;
+(void)rememberMock:(id)arg1 forClass:(Class)arg2 ;
+(id)existingMockForClass:(Class)arg1 ;
+(void)initialize;
-(void)stopMocking;
-(Class)mockObjectClass;
-(void)forwardInvocationForClassObject:(id)arg1 ;
-(void)removeForwarderForClassMethodSelector:(SEL)arg1 ;
-(Class)mockedClass;
-(void)setupClassForClassMethodMocking;
-(void)setupForwarderForClassMethodSelector:(SEL)arg1 ;
-(BOOL)isNSTimeZone__;
-(BOOL)isNSDate__;
-(BOOL)isNSSet__;
-(BOOL)isNSValue__;
-(BOOL)isNSOrderedSet__;
-(Class)class;
-(void)dealloc;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(BOOL)isKindOfClass:(Class)arg1 ;
-(BOOL)conformsToProtocol:(id)arg1 ;
-(id)description;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(id)initWithClass:(Class)arg1 ;
-(BOOL)isNSDictionary__;
-(BOOL)isNSArray__;
-(BOOL)isNSString__;
-(BOOL)isNSNumber__;
-(BOOL)isNSData__;
@end

